package com.logatron.administration.application;

import com.logatron.administration.web.AdminDtos.*;import com.logatron.audit.application.AuditService;import com.logatron.auth.application.*;import com.logatron.auth.persistence.*;import com.logatron.catalog.domain.CatalogEnums.Status;import com.logatron.catalog.persistence.*;import com.logatron.catalog.web.CatalogDtos.*;import com.logatron.common.error.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.http.HttpStatus;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;

@Service public class AdministrationService{
 private final AuthorizationService auth;private final AuditService audit;private final CompanyRepository companies;private final ProjectRepository projects;private final EnvironmentRepository environments;private final ServerRepository servers;private final ServiceRepository services;private final ServiceInstanceRepository instances;private final LogSourceRepository sources;private final UserAccountRepository users;private final RoleRepository roles;private final ProjectMembershipRepository memberships;private final EnvironmentGrantRepository grants;
 public AdministrationService(AuthorizationService auth,AuditService audit,CompanyRepository companies,ProjectRepository projects,EnvironmentRepository environments,ServerRepository servers,ServiceRepository services,ServiceInstanceRepository instances,LogSourceRepository sources,UserAccountRepository users,RoleRepository roles,ProjectMembershipRepository memberships,EnvironmentGrantRepository grants){this.auth=auth;this.audit=audit;this.companies=companies;this.projects=projects;this.environments=environments;this.servers=servers;this.services=services;this.instances=instances;this.sources=sources;this.users=users;this.roles=roles;this.memberships=memberships;this.grants=grants;}
 @Transactional public CreatedResource createProject(Jwt jwt,CreateProjectRequest r,HttpServletRequest request){var actor=auth.authenticatedUser(jwt);var scope=auth.resolveScope(actor);if(!scope.globalAdmin())throw ApiException.denied();var company=companies.findById(r.companyId()).orElseThrow(ApiException::notFound);UUID id=UUID.randomUUID();projects.save(new ProjectEntity(id,company,r.slug(),r.name(),r.classification(),Status.ACTIVE));audit.record(actor,"PROJECT_CREATE","PROJECT",id,id,null,"SUCCESS",request);return new CreatedResource(id);}
 @Transactional public CreatedResource createEnvironment(Jwt jwt,CreateEnvironmentRequest r,HttpServletRequest request){var actor=admin(jwt,r.projectId());var project=projects.findById(r.projectId()).orElseThrow(ApiException::notFound);UUID id=UUID.randomUUID();environments.save(new EnvironmentEntity(id,project,r.code().toUpperCase(Locale.ROOT),r.name(),r.type(),r.sensitivity(),Status.ACTIVE));audit.record(actor,"ENVIRONMENT_CREATE","ENVIRONMENT",id,r.projectId(),id,"SUCCESS",request);return new CreatedResource(id);}
 @Transactional public CreatedResource createServer(Jwt jwt,CreateServerRequest r,HttpServletRequest request){var env=environments.findById(r.environmentId()).orElseThrow(ApiException::notFound);var actor=admin(jwt,env.getProject().getId());UUID id=UUID.randomUUID();servers.save(new ServerEntity(id,env,r.hostId(),r.hostname(),r.ipAddress(),Status.ONLINE,r.labels()));audit.record(actor,"SERVER_CREATE","SERVER",id,env.getProject().getId(),env.getId(),"SUCCESS",request);return new CreatedResource(id);}
 @Transactional public CreatedResource createService(Jwt jwt,CreateServiceRequest r,HttpServletRequest request){var actor=admin(jwt,r.projectId());var project=projects.findById(r.projectId()).orElseThrow(ApiException::notFound);UUID id=UUID.randomUUID();services.save(new ServiceEntity(id,project,r.serviceKey(),r.displayName(),r.owner(),r.criticality(),Status.ACTIVE,r.labels()));audit.record(actor,"SERVICE_CREATE","SERVICE",id,r.projectId(),null,"SUCCESS",request);return new CreatedResource(id);}
 @Transactional public CreatedResource createInstance(Jwt jwt,CreateInstanceRequest r,HttpServletRequest request){var service=services.findById(r.serviceId()).orElseThrow(ApiException::notFound);var server=servers.findById(r.serverId()).orElseThrow(ApiException::notFound);UUID projectId=service.getProject().getId();var actor=admin(jwt,projectId);if(!server.getEnvironment().getProject().getId().equals(projectId))throw new ApiException(HttpStatus.BAD_REQUEST,ErrorCode.INVALID_REQUEST,"Service and server must belong to the same project.");UUID id=UUID.randomUUID();instances.save(new ServiceInstanceEntity(id,service,server,r.instanceKey(),r.version(),Status.RUNNING));audit.record(actor,"SERVICE_INSTANCE_CREATE","SERVICE_INSTANCE",id,projectId,server.getEnvironment().getId(),"SUCCESS",request);return new CreatedResource(id);}
 @Transactional public CreatedResource createLogSource(Jwt jwt,CreateLogSourceRequest r,HttpServletRequest request){var instance=instances.findById(r.serviceInstanceId()).orElseThrow(ApiException::notFound);UUID projectId=instance.getService().getProject().getId();var actor=admin(jwt,projectId);UUID id=UUID.randomUUID();String timezone=timestampTimezone(r.timestampTimezone());sources.save(new LogSourceEntity(id,instance,r.pathPattern(),r.logType(),r.parserProfile(),r.multilineRule(),timezone,r.enabled()));audit.record(actor,"LOG_SOURCE_CREATE","LOG_SOURCE",id,projectId,instance.getServer().getEnvironment().getId(),"SUCCESS",request);return new CreatedResource(id);}
 @Transactional public CreatedResource createMembership(Jwt jwt,CreateMembershipRequest r,HttpServletRequest request){var actor=admin(jwt,r.projectId());var user=users.findById(r.userId()).orElseThrow(ApiException::notFound);var project=projects.findById(r.projectId()).orElseThrow(ApiException::notFound);var role=roles.findByCode(r.role()).orElseThrow(ApiException::notFound);if(r.role()==com.logatron.auth.domain.PlatformRole.ADMIN&&!auth.resolveScope(actor).globalAdmin())throw ApiException.denied();UUID id=UUID.randomUUID();memberships.save(new ProjectMembershipEntity(id,user,project,role,Instant.now(),r.validUntil()));audit.record(actor,"MEMBERSHIP_CREATE","PROJECT_MEMBERSHIP",id,r.projectId(),null,"SUCCESS",request);return new CreatedResource(id);}
 @Transactional public CreatedResource createGrant(Jwt jwt,CreateGrantRequest r,HttpServletRequest request){var membership=memberships.findById(r.membershipId()).orElseThrow(ApiException::notFound);UUID projectId=membership.getProject().getId();var actor=admin(jwt,projectId);var env=environments.findById(r.environmentId()).orElseThrow(ApiException::notFound);if(!env.getProject().getId().equals(projectId))throw new ApiException(HttpStatus.BAD_REQUEST,ErrorCode.INVALID_REQUEST,"Environment must belong to the membership project.");ServiceEntity service=r.serviceId()==null?null:services.findById(r.serviceId()).orElseThrow(ApiException::notFound);if(service!=null&&!service.getProject().getId().equals(projectId))throw new ApiException(HttpStatus.BAD_REQUEST,ErrorCode.INVALID_REQUEST,"Service must belong to the membership project.");UUID id=UUID.randomUUID();grants.save(new EnvironmentGrantEntity(id,membership,env,service));audit.record(actor,"ENVIRONMENT_GRANT_CREATE","ENVIRONMENT_GRANT",id,projectId,env.getId(),"SUCCESS",request);return new CreatedResource(id);}
 @Transactional public void updateProject(Jwt jwt,UUID id,UpdateProjectRequest r,HttpServletRequest request){var project=projects.findById(id).orElseThrow(ApiException::notFound);var actor=admin(jwt,id);project.update(r.name(),r.classification(),r.status());audit.record(actor,"PROJECT_UPDATE","PROJECT",id,id,null,"SUCCESS",request);}
 @Transactional public void updateEnvironment(Jwt jwt,UUID id,UpdateEnvironmentRequest r,HttpServletRequest request){var entity=environments.findById(id).orElseThrow(ApiException::notFound);UUID projectId=entity.getProject().getId();var actor=admin(jwt,projectId);entity.update(r.name(),r.type(),r.sensitivity(),r.status());audit.record(actor,"ENVIRONMENT_UPDATE","ENVIRONMENT",id,projectId,id,"SUCCESS",request);}
 @Transactional public void updateServer(Jwt jwt,UUID id,UpdateServerRequest r,HttpServletRequest request){var entity=servers.findById(id).orElseThrow(ApiException::notFound);UUID projectId=entity.getEnvironment().getProject().getId();var actor=admin(jwt,projectId);entity.update(r.hostname(),r.ipAddress(),r.status(),r.labels());audit.record(actor,"SERVER_UPDATE","SERVER",id,projectId,entity.getEnvironment().getId(),"SUCCESS",request);}
 @Transactional public void updateService(Jwt jwt,UUID id,UpdateServiceRequest r,HttpServletRequest request){var entity=services.findById(id).orElseThrow(ApiException::notFound);UUID projectId=entity.getProject().getId();var actor=admin(jwt,projectId);entity.update(r.displayName(),r.owner(),r.criticality(),r.status(),r.labels());audit.record(actor,"SERVICE_UPDATE","SERVICE",id,projectId,null,"SUCCESS",request);}
 @Transactional public void updateInstance(Jwt jwt,UUID id,UpdateInstanceRequest r,HttpServletRequest request){var entity=instances.findById(id).orElseThrow(ApiException::notFound);UUID projectId=entity.getService().getProject().getId();var actor=admin(jwt,projectId);entity.update(r.version(),r.status());audit.record(actor,"SERVICE_INSTANCE_UPDATE","SERVICE_INSTANCE",id,projectId,entity.getServer().getEnvironment().getId(),"SUCCESS",request);}
 @Transactional public void updateLogSource(Jwt jwt,UUID id,UpdateLogSourceRequest r,HttpServletRequest request){var entity=sources.findById(id).orElseThrow(ApiException::notFound);var instance=entity.getServiceInstance();UUID projectId=instance.getService().getProject().getId();var actor=admin(jwt,projectId);entity.update(r.logType(),r.parserProfile(),r.multilineRule(),timestampTimezone(r.timestampTimezone()),r.enabled());audit.record(actor,"LOG_SOURCE_UPDATE","LOG_SOURCE",id,projectId,instance.getServer().getEnvironment().getId(),"SUCCESS",request);}
 @Transactional public void deleteMembership(Jwt jwt,UUID id,HttpServletRequest request){var entity=memberships.findById(id).orElseThrow(ApiException::notFound);UUID projectId=entity.getProject().getId();var actor=admin(jwt,projectId);memberships.delete(entity);audit.record(actor,"MEMBERSHIP_DELETE","PROJECT_MEMBERSHIP",id,projectId,null,"SUCCESS",request);}
 @Transactional public void deleteGrant(Jwt jwt,UUID id,HttpServletRequest request){var entity=grants.findById(id).orElseThrow(ApiException::notFound);UUID projectId=entity.getMembership().getProject().getId();var actor=admin(jwt,projectId);UUID environmentId=entity.getEnvironment().getId();grants.delete(entity);audit.record(actor,"ENVIRONMENT_GRANT_DELETE","ENVIRONMENT_GRANT",id,projectId,environmentId,"SUCCESS",request);}
 @Transactional(readOnly=true) public List<AccessView> access(Jwt jwt,UUID projectId){admin(jwt,projectId);return memberships.findDetailedByProjectId(projectId).stream().map(m->new AccessView(m.getId(),m.getUser().getId(),m.getUser().getUsername(),m.getUser().getDisplayName(),m.getProject().getId(),m.getProject().getName(),m.getRole().getCode(),m.getValidFrom(),m.getValidUntil())).toList();}
 @Transactional(readOnly=true) public List<UserView> users(Jwt jwt){var actor=auth.authenticatedUser(jwt);if(!auth.resolveScope(actor).projects().values().stream().anyMatch(p->p.roles().contains(com.logatron.auth.domain.PlatformRole.PROJECT_ADMIN))&&!auth.resolveScope(actor).globalAdmin())throw ApiException.denied();return users.findAllByOrderByDisplayName().stream().map(u->new UserView(u.getId(),u.getUsername(),u.getDisplayName(),u.getEmail())).toList();}
 private String timestampTimezone(String value){String normalized=value==null||value.isBlank()?"UTC":value.trim();try{ZoneId.of(normalized);return normalized;}catch(DateTimeException ex){throw new ApiException(HttpStatus.BAD_REQUEST,ErrorCode.INVALID_REQUEST,"timestampTimezone must be a valid IANA timezone, for example UTC or Asia/Kolkata.");}}
 private AuthenticatedUser admin(Jwt jwt,UUID projectId){var actor=auth.authenticatedUser(jwt);auth.requireAdministration(auth.resolveScope(actor),projectId);return actor;}
 public record UserView(UUID id,String username,String displayName,String email){}
}
