package com.logatron.investigation.application;
import com.fasterxml.jackson.databind.ObjectMapper;import com.logatron.audit.application.AuditService;import com.logatron.auth.application.*;import com.logatron.common.error.ApiException;import com.logatron.investigation.application.InvestigationPorts.*;import com.logatron.investigation.configuration.InvestigationProperties;import com.logatron.investigation.domain.InvestigationModels.*;import com.logatron.investigation.persistence.InvestigationRepository;import com.logatron.investigation.web.InvestigationDtos.CreateInvestigationRequest;import org.junit.jupiter.api.*;import org.springframework.security.oauth2.jwt.Jwt;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class InvestigationServiceSecurityTest {
 private final UUID userId=UUID.randomUUID(),project=UUID.randomUUID(),dev=UUID.randomUUID(),prod=UUID.randomUUID();private final AuthorizationService authorization=mock(AuthorizationService.class);private final AuditService audit=mock(AuditService.class);private final LogEvidencePort logs=mock(LogEvidencePort.class);private final TraceEvidencePort traces=mock(TraceEvidencePort.class);private final MetricQueryPort metrics=mock(MetricQueryPort.class);private final AiProvider ai=mock(AiProvider.class);private final InvestigationRepository repository=mock(InvestigationRepository.class);private final AuthenticatedUser actor=new AuthenticatedUser(userId,"issuer","sub","user","User","u@example.test");private final Jwt jwt=mock(Jwt.class);private InvestigationService service;
 @BeforeEach void setup(){var props=new InvestigationProperties("http://prometheus",Duration.ofSeconds(1),20,true,"test","model");service=new InvestigationService(authorization,audit,new ControlledInvestigationPlanner(),logs,traces,metrics,new DeterministicInvestigationEngine(),ai,props,repository,new ObjectMapper().findAndRegisterModules());when(authorization.authenticatedUser(jwt)).thenReturn(actor);when(authorization.resolveScope(actor)).thenReturn(new EffectiveScope(false,Map.of(project,new EffectiveScope.ProjectScope(project,Set.of(),Set.of(dev),Map.of(),false))));doCallRealMethod().when(authorization).require(any(),any());}
 @Test void unauthorizedProjectStopsBeforeAllEvidenceQueries(){assertThatThrownBy(()->service.create(jwt,request(UUID.randomUUID(),dev),null)).isInstanceOf(ApiException.class);verifyNoInteractions(logs,traces,metrics,ai);}
 @Test void unauthorizedProdStopsBeforeAllEvidenceQueries(){assertThatThrownBy(()->service.create(jwt,request(project,prod),null)).isInstanceOf(ApiException.class);verifyNoInteractions(logs,traces,metrics,ai);}
 @Test void providerFailureLeavesDeterministicResultAvailable(){allowEvidence();when(ai.explain(any())).thenThrow(new IllegalStateException("provider down"));var result=service.create(jwt,request(project,dev),null);assertThat(result.deterministic()).isNotNull();assertThat(result.ai().outcome()).isEqualTo("UNAVAILABLE_OR_REJECTED");}
 @Test void malformedProviderOutputIsRejectedWithoutBreakingInvestigation(){allowEvidence();when(ai.explain(any())).thenReturn(new AiResult(null,"test","model",1,"SUCCESS"));assertThat(service.create(jwt,request(project,dev),null).ai().outcome()).isEqualTo("UNAVAILABLE_OR_REJECTED");}
 @Test void unsupportedAiClaimIsRejected(){allowEvidence();var rca=new AiRca("summary","cause",EvidenceStatus.POSSIBLE_HYPOTHESIS,List.of("log:not-in-package"),List.of(),Set.of(),List.of(),"why",List.of(),List.of(),List.of());when(ai.explain(any())).thenReturn(new AiResult(rca,"test","model",1,"SUCCESS"));assertThat(service.create(jwt,request(project,dev),null).ai().outcome()).isEqualTo("UNAVAILABLE_OR_REJECTED");}
 @Test void aiReceivesOnlyTheConfiguredBoundedEvidencePackage(){var many=java.util.stream.IntStream.range(0,50).mapToObj(i->new com.logatron.logquery.web.LogQueryDtos.LogRow(UUID.randomUUID(),Instant.parse("2026-08-30T10:00:00Z").plusSeconds(i),project,"Project",dev,"DEV",UUID.randomUUID(),"host",UUID.randomUUID(),"service","INFO","event "+i,null,"trace",null,"request","correlation","transaction","order","auction")).toList();when(logs.query(any(),any())).thenReturn(many);when(traces.dependencies(eq(jwt),anyList())).thenReturn(List.of());when(metrics.query(any(),any(),anySet())).thenReturn(List.of());when(ai.explain(any())).thenThrow(new IllegalStateException("captured"));service.create(jwt,request(project,dev),null);var captor=org.mockito.ArgumentCaptor.forClass(EvidencePackage.class);verify(ai).explain(captor.capture());assertThat(captor.getValue().rankedEvidence()).hasSize(20);assertThat(captor.getValue().deterministic().evidence()).hasSize(20);assertThat(captor.getValue().deterministic().timeline()).hasSize(20);}
 private void allowEvidence(){when(logs.query(any(),any())).thenReturn(List.of());when(traces.dependencies(eq(jwt),anyList())).thenReturn(List.of());when(metrics.query(any(),any(),anySet())).thenReturn(List.of());}
 private CreateInvestigationRequest request(UUID p,UUID e){return new CreateInvestigationRequest("What failed first?",p,e,Instant.parse("2026-08-30T10:00:00Z"),Instant.parse("2026-08-30T10:30:00Z"),null,null);}
}
