package com.logatron.tracequery.application;
import com.fasterxml.jackson.databind.JsonNode;import com.logatron.audit.application.AuditService;import com.logatron.auth.application.*;import com.logatron.common.error.ApiException;import com.logatron.logquery.application.LogQueryService;import com.logatron.logquery.domain.LogSearchCriteria;import com.logatron.tracequery.infrastructure.TempoClient;import com.logatron.tracequery.web.TraceDtos.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.stereotype.Service;
import java.math.BigInteger;import java.time.*;import java.util.*;import java.util.regex.Pattern;
@Service public class TraceQueryService{
 private static final Pattern TRACE=Pattern.compile("[0-9a-fA-F]{32}");private static final Set<String> SAFE_KEYS=Set.of("http.method","http.route","http.status_code","messaging.system","messaging.destination.name","messaging.operation","db.system","db.operation.name","server.address","error.type","logatron.project.id","project.id","deployment.environment.name");
 private final AuthorizationService authorization;private final LogQueryService logs;private final TempoClient tempo;private final AuditService audit;
 public TraceQueryService(AuthorizationService authorization,LogQueryService logs,TempoClient tempo,AuditService audit){this.authorization=authorization;this.logs=logs;this.tempo=tempo;this.audit=audit;}
 public TraceView get(Jwt jwt,String traceId,HttpServletRequest request){
  String id=traceId==null?"":traceId.trim().toLowerCase(Locale.ROOT);if(!TRACE.matcher(id).matches())throw ApiException.invalid("traceId must contain 32 hexadecimal characters.");AuthenticatedUser actor=authorization.authenticatedUser(jwt);EffectiveScope scope=authorization.resolveScope(actor);
  JsonNode raw=tempo.trace(id);Normalized normalized=normalize(id,raw);Set<UUID> metadataProjects=normalized.projects();
  Instant end=Instant.now().plus(Duration.ofMinutes(1));var criteria=new LogSearchCriteria(null,null,null,null,null,end.minus(Duration.ofHours(24)),end,id,null,null,null,null,null,null,null,null,500,null).normalize(Clock.systemUTC());var related=logs.execute(scope,criteria).items();Set<UUID> logProjects=new HashSet<>();related.forEach(v->logProjects.add(v.projectId()));
  if(metadataProjects.size()>1||metadataProjects.stream().anyMatch(p->!scope.projects().containsKey(p))||(!metadataProjects.isEmpty()&&!logProjects.isEmpty()&&!logProjects.containsAll(metadataProjects))){audit.record(actor,"TRACE_DETAIL","TRACE",null,null,null,"DENIED",Map.of("ownership","ambiguous-or-conflicting"),request);throw ApiException.notFound();}
  Set<UUID> effectiveProjects=metadataProjects.isEmpty()?Set.copyOf(logProjects):metadataProjects;if(effectiveProjects.isEmpty()){audit.record(actor,"TRACE_DETAIL","TRACE",null,null,null,"DENIED",Map.of("ownership","no-authorized-metadata-or-log-evidence"),request);throw ApiException.notFound();}
  audit.record(actor,"TRACE_DETAIL","TRACE",null,effectiveProjects.size()==1?effectiveProjects.iterator().next():null,null,"SUCCESS",Map.of("ownership",metadataProjects.isEmpty()?"related-log-evidence":"resource-metadata","spanCount",String.valueOf(normalized.spans().size())),request);return new TraceView(id,normalized.spans(),effectiveProjects);
 }
 private Normalized normalize(String traceId,JsonNode raw){List<JsonNode> batches=new ArrayList<>();JsonNode source=raw.has("batches")?raw.get("batches"):raw.get("resourceSpans");if(source!=null&&source.isArray())source.forEach(batches::add);List<SpanView> spans=new ArrayList<>();Set<UUID> projects=new HashSet<>();
  for(JsonNode batch:batches){Map<String,String> resource=attributes(batch.path("resource").path("attributes"));String project=first(resource,"logatron.project.id","project.id");if(project!=null)try{projects.add(UUID.fromString(project));}catch(IllegalArgumentException ex){throw ApiException.notFound();}String service=Optional.ofNullable(resource.get("service.name")).orElse("unknown-service");JsonNode groups=batch.has("scopeSpans")?batch.get("scopeSpans"):batch.get("instrumentationLibrarySpans");if(groups==null)continue;for(JsonNode group:groups)for(JsonNode span:group.path("spans")){String returnedTrace=otelId(span,"traceId");if(returnedTrace!=null&&!traceId.equalsIgnoreCase(returnedTrace))continue;long start=nanos(span.path("startTimeUnixNano")),end=nanos(span.path("endTimeUnixNano"));String status=status(span.path("status"));spans.add(new SpanView(otelId(span,"spanId"),otelId(span,"parentSpanId"),service,span.path("name").asText("unnamed"),instant(start),instant(end),Math.max(0,(end-start)/1_000),status,safe(attributes(span.path("attributes")))));}}
  spans.sort(Comparator.comparing(SpanView::start,Comparator.nullsLast(Comparator.naturalOrder())));return new Normalized(List.copyOf(spans),Set.copyOf(projects));
 }
 private Map<String,String> attributes(JsonNode values){Map<String,String> result=new LinkedHashMap<>();if(values!=null&&values.isArray())for(JsonNode a:values){String key=a.path("key").asText();JsonNode v=a.path("value");String text=null;for(String field:List.of("stringValue","intValue","doubleValue","boolValue"))if(v.has(field)){text=v.get(field).asText();break;}if(!key.isBlank()&&text!=null)result.put(key,text);}return result;}
 private Map<String,String> safe(Map<String,String> values){Map<String,String> out=new LinkedHashMap<>();values.forEach((k,v)->{String lower=k.toLowerCase(Locale.ROOT);if((SAFE_KEYS.contains(k)||k.startsWith("logatron."))&&!lower.contains("secret")&&!lower.contains("password")&&!lower.contains("token")&&!lower.equals("db.statement"))out.put(k,v.substring(0,Math.min(v.length(),500)));});return Map.copyOf(out);}
 private static String first(Map<String,String> map,String...keys){for(String k:keys)if(map.containsKey(k))return map.get(k);return null;}private static String otelId(JsonNode n,String f){if(!n.hasNonNull(f)||n.get(f).asText().isBlank())return null;String value=n.get(f).asText();if(value.matches("[0-9a-fA-F]+"))return value.toLowerCase(Locale.ROOT);try{return HexFormat.of().formatHex(Base64.getDecoder().decode(value));}catch(IllegalArgumentException ex){return null;}}private static long nanos(JsonNode n){if(n.isNumber())return n.asLong();try{return new BigInteger(n.asText("0")).longValueExact();}catch(Exception ex){return 0;}}private static Instant instant(long nanos){return nanos<=0?null:Instant.ofEpochSecond(Math.floorDiv(nanos,1_000_000_000L),Math.floorMod(nanos,1_000_000_000L));}private static String status(JsonNode n){String code=n.path("code").asText("UNSET");return code.equals("2")||code.endsWith("ERROR")?"ERROR":code.equals("1")||code.endsWith("OK")?"OK":"UNSET";}private record Normalized(List<SpanView> spans,Set<UUID> projects){}
}
