package com.logatron.tracequery.application;
import com.fasterxml.jackson.databind.ObjectMapper;import com.logatron.audit.application.AuditService;import com.logatron.auth.application.*;import com.logatron.auth.domain.PlatformRole;import com.logatron.common.error.ApiException;import com.logatron.logquery.application.LogQueryService;import com.logatron.logquery.web.LogQueryDtos.*;import com.logatron.tracequery.infrastructure.TempoClient;import org.junit.jupiter.api.*;import org.springframework.security.oauth2.jwt.Jwt;import java.time.Instant;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class TraceQueryServiceSecurityTest{
 private final AuthorizationService authorization=mock(AuthorizationService.class);private final LogQueryService logs=mock(LogQueryService.class);private final TempoClient tempo=mock(TempoClient.class);private final AuditService audit=mock(AuditService.class);private final Jwt jwt=mock(Jwt.class);private final UUID actorId=UUID.randomUUID(),project=UUID.fromString("10000000-0000-0000-0000-000000000001"),environment=UUID.fromString("20000000-0000-0000-0000-000000000003"),service=UUID.fromString("40000000-0000-0000-0000-000000000008");
 private TraceQueryService subject;@BeforeEach void setup(){subject=new TraceQueryService(authorization,logs,tempo,audit);AuthenticatedUser actor=new AuthenticatedUser(actorId,"issuer","subject","user","User",null);EffectiveScope scope=new EffectiveScope(false,Map.of(project,new EffectiveScope.ProjectScope(project,Set.of(PlatformRole.PRODUCTION_SUPPORT),Set.of(environment),Map.of(),false)));when(authorization.authenticatedUser(jwt)).thenReturn(actor);when(authorization.resolveScope(actor)).thenReturn(scope);}
 @Test void unauthorizedTraceNeverTouchesTempo(){when(logs.execute(any(),any())).thenReturn(new SearchPage(List.of(),null,false));assertThatThrownBy(()->subject.get(jwt,"0123456789abcdef0123456789abcdef",null)).isInstanceOf(ApiException.class);verifyNoInteractions(tempo);}
 @Test void ambiguousProjectMetadataFailsClosed(){LogRow evidence=new LogRow(UUID.randomUUID(),Instant.now(),project,"Project",environment,"PROD",null,"server",service,"settlement","ERROR","failed",null,"0123456789abcdef0123456789abcdef",null,null,null,null,null,null);when(logs.execute(any(),any())).thenReturn(new SearchPage(List.of(evidence),null,false));String json="{\"resourceSpans\":[{\"resource\":{\"attributes\":[{\"key\":\"logatron.project.id\",\"value\":{\"stringValue\":\"10000000-0000-0000-0000-000000000001\"}}]}},{\"resource\":{\"attributes\":[{\"key\":\"logatron.project.id\",\"value\":{\"stringValue\":\"10000000-0000-0000-0000-000000000002\"}}]}}]}";try{when(tempo.trace(anyString())).thenReturn(new ObjectMapper().readTree(json));}catch(Exception ex){throw new RuntimeException(ex);}assertThatThrownBy(()->subject.get(jwt,"0123456789abcdef0123456789abcdef",null)).isInstanceOf(ApiException.class);}
 @Test void tempoProtobufJsonBase64IdsAreNormalizedToHex(){String trace="0123456789abcdef0123456789abcdef",span="0123456789abcdef";LogRow evidence=new LogRow(UUID.randomUUID(),Instant.now(),project,"Project",environment,"PROD",null,"server",service,"settlement","INFO","ok",null,trace,null,null,null,null,null,null);when(logs.execute(any(),any())).thenReturn(new SearchPage(List.of(evidence),null,false));String trace64=Base64.getEncoder().encodeToString(HexFormat.of().parseHex(trace)),span64=Base64.getEncoder().encodeToString(HexFormat.of().parseHex(span));String json="{\"batches\":[{\"resource\":{\"attributes\":[{\"key\":\"logatron.project.id\",\"value\":{\"stringValue\":\""+project+"\"}}]},\"scopeSpans\":[{\"spans\":[{\"traceId\":\""+trace64+"\",\"spanId\":\""+span64+"\",\"name\":\"work\",\"startTimeUnixNano\":\"1000000000\",\"endTimeUnixNano\":\"1001000000\"}]}]}]}";try{when(tempo.trace(trace)).thenReturn(new ObjectMapper().readTree(json));}catch(Exception ex){throw new RuntimeException(ex);}var view=subject.get(jwt,trace,null);assertThat(view.spans()).singleElement().extracting(v->v.spanId()).isEqualTo(span);}
}
