ALTER TABLE collector_agent
    ADD COLUMN applied_config_version BIGINT;

CREATE TABLE collector_config_revision (
    id UUID PRIMARY KEY,
    agent_id UUID NOT NULL REFERENCES collector_agent(id) ON DELETE CASCADE,
    config_version BIGINT NOT NULL,
    config_hash VARCHAR(64) NOT NULL,
    config_yaml TEXT NOT NULL,
    source_count INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_collector_config_revision_version UNIQUE (agent_id, config_version),
    CONSTRAINT uq_collector_config_revision_hash UNIQUE (agent_id, config_hash)
);

CREATE INDEX idx_collector_config_revision_agent_created
    ON collector_config_revision(agent_id, created_at DESC);

COMMENT ON TABLE collector_config_revision IS
    'Immutable, server-specific collector desired-state snapshots generated by LOG-A-TRON.';
