package com.logatron.logquery.application;
import com.logatron.audit.application.AuditService;import com.logatron.auth.application.*;import com.logatron.common.error.ApiException;import com.logatron.logquery.configuration.LogQueryProperties;import com.logatron.logquery.domain.LogSearchCriteria;import com.logatron.logquery.web.LogQueryDtos.LogRow;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.stereotype.Service;import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;
import java.time.*;import java.util.*;import java.util.concurrent.Semaphore;import java.util.concurrent.atomic.AtomicBoolean;
@Service
public class LiveTailService{
 private final LogQueryService logs;private final AuthorizationService authorization;private final AuditService audit;private final LogQueryProperties properties;private final Semaphore connections;
 public LiveTailService(LogQueryService logs,AuthorizationService authorization,AuditService audit,LogQueryProperties properties){this.logs=logs;this.authorization=authorization;this.audit=audit;this.properties=properties;this.connections=new Semaphore(properties.maxLiveConnections(),true);}
 public SseEmitter open(Jwt jwt,LogSearchCriteria input,HttpServletRequest request){
  if(!connections.tryAcquire())throw ApiException.rateLimited();AuthenticatedUser actor=authorization.authenticatedUser(jwt);EffectiveScope scope=authorization.resolveScope(actor);LogSearchCriteria.Normalized requested=input.normalize(Clock.systemUTC());if(requested.projectId()!=null)authorization.require(scope,new RequestedResourceScope(requested.projectId(),requested.environmentId(),requested.serviceId()));if(scope.projects().isEmpty()){connections.release();throw ApiException.denied();}
  SseEmitter emitter=new SseEmitter(properties.liveMaxDuration().toMillis());AtomicBoolean closed=new AtomicBoolean();emitter.onCompletion(()->closed.set(true));emitter.onTimeout(()->closed.set(true));emitter.onError(e->closed.set(true));audit.record(actor,"LOG_LIVE_OPEN","LOG_QUERY",null,requested.projectId(),requested.environmentId(),"SUCCESS",Map.of("bestEffort","true","maxSeconds",String.valueOf(properties.liveMaxDuration().toSeconds())),request);
  Thread.startVirtualThread(()->{Instant started=Instant.now(),watermark=started;LinkedHashSet<UUID> sent=new LinkedHashSet<>();try{emitter.send(SseEmitter.event().name("status").data(Map.of("state","connected","bestEffort",true,"maxDurationSeconds",properties.liveMaxDuration().toSeconds())));while(!closed.get()&&Duration.between(started,Instant.now()).compareTo(properties.liveMaxDuration())<0){Instant now=Instant.now();LogSearchCriteria poll=new LogSearchCriteria(requested.projectId(),requested.environmentId(),requested.serverId(),requested.serviceId(),requested.level(),watermark.minusMillis(1),now,requested.traceId(),requested.spanId(),requested.requestId(),requested.correlationId(),requested.transactionId(),requested.orderToken(),requested.auctionId(),requested.exceptionType(),requested.text(),Math.min(properties.liveBufferCap(),500),null);List<LogRow> rows=new ArrayList<>(logs.execute(scope,poll.normalize(Clock.systemUTC())).items());Collections.reverse(rows);for(LogRow row:rows)if(sent.add(row.eventId()))emitter.send(SseEmitter.event().id(row.eventId().toString()).name("log").data(row));while(sent.size()>properties.liveBufferCap())sent.remove(sent.iterator().next());watermark=now;Thread.sleep(properties.livePollInterval());}if(!closed.get())emitter.send(SseEmitter.event().name("status").data(Map.of("state","duration-limit","reconnect",true)));emitter.complete();}catch(InterruptedException ex){Thread.currentThread().interrupt();emitter.complete();}catch(Exception ex){try{emitter.send(SseEmitter.event().name("error").data(Map.of("message","Live tail interrupted; persisted search remains available.")));}catch(Exception ignored){}emitter.completeWithError(ex);}finally{connections.release();audit.record(actor,"LOG_LIVE_CLOSE","LOG_QUERY",null,requested.projectId(),requested.environmentId(),"SUCCESS",Map.of("bestEffort","true"),null);}});
  return emitter;
 }
}
