package com.logatron.logquery.application;

import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.*;import com.logatron.audit.application.AuditService;import com.logatron.auth.application.*;import com.logatron.common.error.ApiException;import com.logatron.logquery.domain.*;import com.logatron.logquery.infrastructure.*;import com.logatron.logquery.web.LogQueryDtos.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.stereotype.Service;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;

@Service
public class LogQueryService{
 private static final String ROW_COLUMNS="toString(event_id) eventId,toString(timestamp,'UTC') timestamp,toString(project_id) projectId,project,toString(environment_id) environmentId,environment,toString(server_id) serverId,server,toString(service_id) serviceId,service,toString(level) level,message,exception_type exceptionType,trace_id traceId,span_id spanId,request_id requestId,correlation_id correlationId,transaction_id transactionId,order_token orderToken,auction_id auctionId";
 private final AuthorizationService authorization;private final AuditService audit;private final ClickHouseQueryClient clickhouse;private final AuthorizedLogSql sql;private final ObjectMapper mapper;private final Clock clock;
 @Autowired public LogQueryService(AuthorizationService authorization,AuditService audit,ClickHouseQueryClient clickhouse,AuthorizedLogSql sql,ObjectMapper mapper){this(authorization,audit,clickhouse,sql,mapper,Clock.systemUTC());}
 LogQueryService(AuthorizationService authorization,AuditService audit,ClickHouseQueryClient clickhouse,AuthorizedLogSql sql,ObjectMapper mapper,Clock clock){this.authorization=authorization;this.audit=audit;this.clickhouse=clickhouse;this.sql=sql;this.mapper=mapper;this.clock=clock;}
 public SearchPage search(Jwt jwt,LogSearchCriteria criteria,HttpServletRequest request){var actor=authorization.authenticatedUser(jwt);var normalized=criteria.normalize(clock);var scope=scope(actor,normalized);try{SearchPage page=execute(scope,normalized);record(actor,"LOG_SEARCH",normalized,"SUCCESS",page.items().size(),request);return page;}catch(RuntimeException ex){record(actor,"LOG_SEARCH",normalized,"FAILED",0,request);throw ex;}}
 public LogDetail detail(Jwt jwt,UUID eventId,HttpServletRequest request){var actor=authorization.authenticatedUser(jwt);var scope=authorization.resolveScope(actor);try{LogDetail detail=findDetail(scope,eventId);audit.record(actor,"LOG_DETAIL","LOG_EVENT",eventId,detail.projectId(),detail.environmentId(),"SUCCESS",Map.of("scopeDigest",scopeDigest(scope)),request);return detail;}catch(RuntimeException ex){audit.record(actor,"LOG_DETAIL","LOG_EVENT",eventId,null,null,"DENIED",Map.of("scopeDigest",scopeDigest(scope)),request);throw ex;}}
 public ContextResponse context(Jwt jwt,ContextRequest input,HttpServletRequest request){if(input==null||input.eventId()==null)throw ApiException.invalid("eventId is required.");int before=bounded(input.before(),50),after=bounded(input.after(),50);var actor=authorization.authenticatedUser(jwt);var scope=authorization.resolveScope(actor);LogDetail anchor=findDetail(scope,input.eventId());var c=new LogSearchCriteria(anchor.projectId(),anchor.environmentId(),anchor.serverId(),anchor.serviceId(),null,anchor.timestamp().minus(Duration.ofMinutes(5)),anchor.timestamp().plus(Duration.ofMinutes(5)),null,null,null,null,null,null,null,null,null,Math.min(500,before+after+10),null).normalize(clock);List<LogRow> rows=execute(scope,c).items();List<LogRow> older=rows.stream().filter(v->v.timestamp().isBefore(anchor.timestamp())&&!v.eventId().equals(anchor.eventId())).limit(before).toList();List<LogRow> newer=rows.stream().filter(v->v.timestamp().isAfter(anchor.timestamp())&&!v.eventId().equals(anchor.eventId())).sorted(Comparator.comparing(LogRow::timestamp)).limit(after).toList();audit.record(actor,"LOG_CONTEXT","LOG_EVENT",anchor.eventId(),anchor.projectId(),anchor.environmentId(),"SUCCESS",Map.of("scopeDigest",scopeDigest(scope),"before",String.valueOf(before),"after",String.valueOf(after)),request);return new ContextResponse(anchor,older,newer);}
 public SearchPage correlate(Jwt jwt,CorrelateRequest input,HttpServletRequest request){if(input==null||input.value()==null||input.value().isBlank())throw ApiException.invalid("A correlation value is required.");if(input.value().length()>200)throw ApiException.invalid("The correlation value is too long.");CorrelationIdentifier identifier=CorrelationIdentifier.parse(input.identifierType());LogSearchCriteria criteria=correlationCriteria(input,identifier);var actor=authorization.authenticatedUser(jwt);var normalized=criteria.normalize(clock);var scope=scope(actor,normalized);SearchPage result=execute(scope,normalized);record(actor,"LOG_CORRELATION",normalized,"SUCCESS",result.items().size(),request);return result;}
 public Overview overview(Jwt jwt,OverviewRequest input,HttpServletRequest request){var actor=authorization.authenticatedUser(jwt);Instant to=input==null||input.to()==null?clock.instant():input.to(),from=input==null||input.from()==null?to.minus(Duration.ofMinutes(30)):input.from();LogSearchCriteria.Normalized c=new LogSearchCriteria(input==null?null:input.projectId(),input==null?null:input.environmentId(),null,input==null?null:input.serviceId(),null,from,to,null,null,null,null,null,null,null,null,null,100,null).normalize(clock);EffectiveScope scope=scope(actor,c);var authorized=sql.scope(scope,c);Map<String,String> p=new LinkedHashMap<>(authorized.parameters());p.put("from",AuthorizedLogSql.dateTime64(c.from()));p.put("to",AuthorizedLogSql.dateTime64(c.to()));String service="";if(c.serviceId()!=null){service=" AND service_id={filterService:UUID}";p.put("filterService",c.serviceId().toString());}
  String base=" FROM log_counts_1m WHERE "+authorized.sql()+" AND bucket >= {from:DateTime64(3,'UTC')} AND bucket < {to:DateTime64(3,'UTC')}"+service;
  JsonNode totals=first(clickhouse.query("SELECT countMerge(count) total,countMergeIf(count,level=4) warn,countMergeIf(count,level IN (5,6)) error"+base,p));
  List<TrendPoint> trend=clickhouse.query("SELECT toString(bucket,'UTC') bucket,countMerge(count) total,countMergeIf(count,level=4) warn,countMergeIf(count,level IN (5,6)) error"+base+" GROUP BY bucket ORDER BY bucket",p).stream().map(v->new TrendPoint(instant(v,"bucket"),longValue(v,"total"),longValue(v,"warn"),longValue(v,"error"))).toList();
  List<ServiceCount> top=clickhouse.query("SELECT toString(service_id) serviceId,countMerge(count) errors"+base+" AND level IN (5,6) GROUP BY service_id ORDER BY errors DESC LIMIT 10",p).stream().map(v->{UUID id=uuid(v,"serviceId");return new ServiceCount(id,id.toString(),longValue(v,"errors"));}).toList();
  audit.record(actor,"LOG_OVERVIEW","LOG_AGGREGATE",null,c.projectId(),c.environmentId(),"SUCCESS",Map.of("scopeDigest",scopeDigest(scope)),request);return new Overview(longValue(totals,"total"),longValue(totals,"warn"),longValue(totals,"error"),trend,top);
 }
 public SearchPage execute(EffectiveScope scope,LogSearchCriteria.Normalized c){var parts=sql.filtered(scope,c);Map<String,String> p=new LinkedHashMap<>(parts.parameters());p.put("limit",String.valueOf(c.pageSize()+1));String query="SELECT "+ROW_COLUMNS+" FROM logs_local WHERE "+parts.where()+" ORDER BY timestamp DESC,event_id DESC,ingested_at DESC LIMIT 1 BY event_id LIMIT {limit:UInt32}";List<LogRow> all=clickhouse.query(query,p).stream().map(this::row).toList();boolean more=all.size()>c.pageSize();List<LogRow> items=more?all.subList(0,c.pageSize()):all;LogSearchCriteria.Cursor next=more&&!items.isEmpty()?new LogSearchCriteria.Cursor(items.getLast().timestamp(),items.getLast().eventId()):null;return new SearchPage(List.copyOf(items),next,more);}
 public LogDetail findDetail(EffectiveScope scope,UUID eventId){Instant end=clock.instant().plus(Duration.ofMinutes(1));var c=new LogSearchCriteria(null,null,null,null,null,end.minus(Duration.ofHours(24)),end,null,null,null,null,null,null,null,null,null,1,null).normalize(clock);var auth=sql.scope(scope,c);Map<String,String> p=new LinkedHashMap<>(auth.parameters());p.put("event",eventId.toString());String q="SELECT toString(event_id) eventId,toString(timestamp,'UTC') timestamp,toString(observed_timestamp,'UTC') observedTimestamp,toString(ingested_at,'UTC') ingestedAt,toString(project_id) projectId,project,toString(environment_id) environmentId,environment,toString(server_id) serverId,server,hostname,toString(service_id) serviceId,service,service_instance serviceInstance,toString(level) level,logger,thread,message,exception_type exceptionType,stack_trace stackTrace,trace_id traceId,span_id spanId,request_id requestId,correlation_id correlationId,transaction_id transactionId,order_token orderToken,auction_id auctionId,attributes,resource_attributes resourceAttributes,log_file logFile,log_type logType,data_classification dataClassification,masking_applied maskingApplied FROM logs_local WHERE "+auth.sql()+" AND event_id={event:UUID} ORDER BY ingested_at DESC LIMIT 1";List<JsonNode> rows=clickhouse.query(q,p);if(rows.isEmpty())throw ApiException.notFound();return detail(rows.getFirst());}
 private EffectiveScope scope(AuthenticatedUser actor,LogSearchCriteria.Normalized c){EffectiveScope s=authorization.resolveScope(actor);if(c.projectId()!=null)authorization.require(s,new RequestedResourceScope(c.projectId(),c.environmentId(),c.serviceId()));if(s.projects().isEmpty())throw ApiException.denied();return s;}
 private LogSearchCriteria correlationCriteria(CorrelateRequest i,CorrelationIdentifier id){String[] v=new String[6];v[id.ordinal()]=i.value().trim();return new LogSearchCriteria(i.projectId(),i.environmentId(),null,null,null,i.from(),i.to(),v[0],null,v[1],v[2],v[3],v[4],v[5],null,null,i.pageSize(),i.cursor());}
 private int bounded(Integer value,int fallback){int v=value==null?fallback:value;if(v<0||v>100)throw ApiException.invalid("Context counts must be between 0 and 100.");return v;}
 private LogRow row(JsonNode n){return new LogRow(uuid(n,"eventId"),instant(n,"timestamp"),uuid(n,"projectId"),text(n,"project"),uuid(n,"environmentId"),text(n,"environment"),nullableUuid(n,"serverId"),text(n,"server"),uuid(n,"serviceId"),text(n,"service"),text(n,"level"),text(n,"message"),text(n,"exceptionType"),text(n,"traceId"),text(n,"spanId"),text(n,"requestId"),text(n,"correlationId"),text(n,"transactionId"),text(n,"orderToken"),text(n,"auctionId"));}
 private LogDetail detail(JsonNode n){return new LogDetail(uuid(n,"eventId"),instant(n,"timestamp"),instant(n,"observedTimestamp"),instant(n,"ingestedAt"),uuid(n,"projectId"),text(n,"project"),uuid(n,"environmentId"),text(n,"environment"),nullableUuid(n,"serverId"),text(n,"server"),text(n,"hostname"),uuid(n,"serviceId"),text(n,"service"),text(n,"serviceInstance"),text(n,"level"),text(n,"logger"),text(n,"thread"),text(n,"message"),text(n,"exceptionType"),text(n,"stackTrace"),text(n,"traceId"),text(n,"spanId"),text(n,"requestId"),text(n,"correlationId"),text(n,"transactionId"),text(n,"orderToken"),text(n,"auctionId"),map(n,"attributes"),map(n,"resourceAttributes"),text(n,"logFile"),text(n,"logType"),text(n,"dataClassification"),n.path("maskingApplied").asInt()==1||n.path("maskingApplied").asBoolean());}
 private Map<String,String> map(JsonNode n,String field){JsonNode v=n.get(field);return v==null||v.isNull()?Map.of():mapper.convertValue(v,new TypeReference<Map<String,String>>(){});}private static String text(JsonNode n,String f){JsonNode v=n.get(f);return v==null||v.isNull()?null:v.asText();}private static UUID uuid(JsonNode n,String f){return UUID.fromString(text(n,f));}private static UUID nullableUuid(JsonNode n,String f){String v=text(n,f);return v==null||v.isBlank()||v.equals("00000000-0000-0000-0000-000000000000")?null:UUID.fromString(v);}private static long longValue(JsonNode n,String f){return n==null?0:n.path(f).asLong();}private static JsonNode first(List<JsonNode> rows){return rows.isEmpty()?null:rows.getFirst();}
 private static Instant instant(JsonNode n,String f){String v=text(n,f);if(v==null)return null;if(v.endsWith("Z"))return Instant.parse(v);return Instant.parse(v.replace(' ','T')+"Z");}
 private void record(AuthenticatedUser actor,String action,LogSearchCriteria.Normalized c,String outcome,int rows,HttpServletRequest request){audit.record(actor,action,"LOG_QUERY",null,c.projectId(),c.environmentId(),outcome,Map.of("criteriaDigest",digest(c),"scope",String.valueOf(c.projectId()),"from",c.from().toString(),"to",c.to().toString(),"rows",String.valueOf(rows)),request);}
 private String digest(Object value){try{byte[] data=mapper.writeValueAsBytes(value);return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(data));}catch(Exception ex){return "unavailable";}}private String scopeDigest(EffectiveScope scope){return digest(scope.projects().keySet());}
}
