package com.logatron.logquery.application;
import com.fasterxml.jackson.databind.ObjectMapper;import com.logatron.audit.application.AuditService;import com.logatron.auth.application.*;import com.logatron.auth.persistence.UserAccountRepository;import com.logatron.catalog.persistence.ProjectRepository;import com.logatron.common.error.ApiException;import com.logatron.logquery.domain.LogSearchCriteria;import com.logatron.logquery.persistence.*;import com.logatron.logquery.web.SavedSearchDtos.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Clock;import java.util.*;
@Service
public class SavedSearchService{
 private final SavedSearchRepository searches;private final UserAccountRepository users;private final ProjectRepository projects;private final AuthorizationService authorization;private final AuditService audit;private final ObjectMapper mapper;
 public SavedSearchService(SavedSearchRepository searches,UserAccountRepository users,ProjectRepository projects,AuthorizationService authorization,AuditService audit,ObjectMapper mapper){this.searches=searches;this.users=users;this.projects=projects;this.authorization=authorization;this.audit=audit;this.mapper=mapper;}
 @Transactional(readOnly=true)public List<SavedSearchView> list(Jwt jwt){var actor=authorization.authenticatedUser(jwt);var scope=authorization.resolveScope(actor);return searches.findAllByOrderByUpdatedAtDesc().stream().filter(s->visible(s,actor,scope)).map(this::view).toList();}
 @Transactional(readOnly=true)public SavedSearchView get(Jwt jwt,UUID id){var actor=authorization.authenticatedUser(jwt);var scope=authorization.resolveScope(actor);SavedSearchEntity s=searches.findById(id).orElseThrow(ApiException::notFound);if(!visible(s,actor,scope))throw ApiException.notFound();return view(s);}
 @Transactional public SavedSearchView create(Jwt jwt,SaveRequest request,HttpServletRequest http){var actor=authorization.authenticatedUser(jwt);Validated v=validate(request);authorization.require(authorization.resolveScope(actor),new RequestedResourceScope(v.criteria.projectId(),v.criteria.environmentId(),v.criteria.serviceId()));var owner=users.findById(actor.id()).orElseThrow(ApiException::notFound);var project=projects.findById(v.criteria.projectId()).orElseThrow(ApiException::notFound);SavedSearchEntity saved=searches.save(new SavedSearchEntity(owner,project,v.name,v.visibility,mapper.valueToTree(v.criteria)));audit.record(actor,"SAVED_SEARCH_CREATE","SAVED_SEARCH",saved.getId(),project.getId(),v.criteria.environmentId(),"SUCCESS",Map.of("visibility",v.visibility),http);return view(saved);}
 @Transactional public SavedSearchView update(Jwt jwt,UUID id,SaveRequest request,HttpServletRequest http){var actor=authorization.authenticatedUser(jwt);SavedSearchEntity saved=searches.findById(id).orElseThrow(ApiException::notFound);if(!saved.getOwner().getId().equals(actor.id()))throw ApiException.notFound();Validated v=validate(request);if(!saved.getProject().getId().equals(v.criteria.projectId()))throw ApiException.invalid("A saved search cannot be moved to another project.");authorization.require(authorization.resolveScope(actor),new RequestedResourceScope(v.criteria.projectId(),v.criteria.environmentId(),v.criteria.serviceId()));if(searches.existsByOwnerIdAndNameIgnoreCaseAndIdNot(actor.id(),v.name,id))throw ApiException.invalid("A saved search with this name already exists.");saved.update(v.name,v.visibility,mapper.valueToTree(v.criteria));audit.record(actor,"SAVED_SEARCH_UPDATE","SAVED_SEARCH",id,v.criteria.projectId(),v.criteria.environmentId(),"SUCCESS",Map.of("visibility",v.visibility),http);return view(saved);}
 @Transactional public void delete(Jwt jwt,UUID id,HttpServletRequest http){var actor=authorization.authenticatedUser(jwt);SavedSearchEntity saved=searches.findById(id).orElseThrow(ApiException::notFound);if(!saved.getOwner().getId().equals(actor.id()))throw ApiException.notFound();UUID project=saved.getProject().getId();searches.delete(saved);audit.record(actor,"SAVED_SEARCH_DELETE","SAVED_SEARCH",id,project,null,"SUCCESS",http);}
 private boolean visible(SavedSearchEntity s,AuthenticatedUser actor,EffectiveScope scope){if(s.getOwner().getId().equals(actor.id()))return true;return "PROJECT".equals(s.getVisibility())&&scope.projects().containsKey(s.getProject().getId());}
 private Validated validate(SaveRequest request){if(request==null||request.criteria()==null)throw ApiException.invalid("criteria is required.");String name=request.name()==null?"":request.name().trim();if(name.isEmpty()||name.length()>120)throw ApiException.invalid("name must be between 1 and 120 characters.");String visibility=request.visibility()==null?"OWNER":request.visibility().trim().toUpperCase(Locale.ROOT);if(!Set.of("OWNER","PROJECT").contains(visibility))throw ApiException.invalid("visibility must be OWNER or PROJECT.");LogSearchCriteria criteria=request.criteria();var n=criteria.normalize(Clock.systemUTC());if(n.projectId()==null)throw ApiException.invalid("A saved search requires a projectId.");return new Validated(name,visibility,criteria);}
 private SavedSearchView view(SavedSearchEntity s){try{return new SavedSearchView(s.getId(),s.getOwner().getId(),s.getProject().getId(),s.getName(),s.getVisibility(),mapper.treeToValue(s.getCriteria(),LogSearchCriteria.class),s.getCreatedAt(),s.getUpdatedAt());}catch(Exception ex){throw ApiException.unavailable("Saved search storage");}}
 private record Validated(String name,String visibility,LogSearchCriteria criteria){}
}
