export interface EnvironmentAccess { environmentId:string; code:string; name:string }
export interface ProjectAccess { projectId:string; projectName:string; roles:string[]; environments:EnvironmentAccess[] }
export interface MeResponse { user:{id:string;username:string;displayName:string;email:string}; roles:string[]; projects:ProjectAccess[] }
export interface ProjectView { id:string;slug:string;name:string;classification:string;status:string;environments:number;servers:number;services:number;instances:number }
export interface EnvironmentView {id:string;projectId:string;code:string;name:string;type:string;sensitivity:string;status:string}
export interface ServerView {id:string;environmentId:string;hostId:string;hostname:string;ipAddress:string;status:string;labels:Record<string,string>;collectorStatus:string}
export interface ServiceView {id:string;projectId:string;serviceKey:string;displayName:string;owner:string;criticality:string;status:string;labels:Record<string,string>}
export interface ServiceInstanceView {id:string;serviceId:string;serviceName:string;serverId:string;hostname:string;instanceKey:string;version:string;status:string}
export interface LogSourceView {id:string;serviceInstanceId:string;pathPattern:string;logType:string;parserProfile:string;multilineRule:string;timestampTimezone:string;enabled:boolean;configVersion:number}
export interface ApiError {timestamp:string;status:number;errorCode:string;message:string;traceId:string;fieldErrors:{field:string;code:string;message:string}[]}
export interface LogCursor {timestamp:string;eventId:string}
export interface LogSearchCriteria {projectId?:string|null;environmentId?:string|null;serverId?:string|null;serviceId?:string|null;level?:string|null;from?:string|null;to?:string|null;traceId?:string|null;spanId?:string|null;requestId?:string|null;correlationId?:string|null;transactionId?:string|null;orderToken?:string|null;auctionId?:string|null;exceptionType?:string|null;text?:string|null;pageSize?:number;cursor?:LogCursor|null}
export interface LogRow {eventId:string;timestamp:string;projectId:string;project:string;environmentId:string;environment:string;serverId:string|null;server:string;serviceId:string;service:string;level:string;message:string;exceptionType:string|null;traceId:string|null;spanId:string|null;requestId:string|null;correlationId:string|null;transactionId:string|null;orderToken:string|null;auctionId:string|null}
export interface LogDetail extends LogRow {observedTimestamp:string;ingestedAt:string;hostname:string;serviceInstance:string;logger:string|null;thread:string|null;stackTrace:string|null;attributes:Record<string,string>;resourceAttributes:Record<string,string>;logFile:string;logType:string;dataClassification:string;maskingApplied:boolean}
export interface SearchPage {items:LogRow[];nextCursor:LogCursor|null;hasMore:boolean}
export interface ContextResponse {anchor:LogDetail;before:LogRow[];after:LogRow[]}
export interface SavedSearch {id:string;ownerUserId:string;projectId:string;name:string;visibility:'OWNER'|'PROJECT';criteria:LogSearchCriteria;createdAt:string;updatedAt:string}
export interface Overview {total:number;warn:number;error:number;trend:{bucket:string;total:number;warn:number;error:number}[];topServicesByErrors:{serviceId:string;service:string;errors:number}[]}
export interface TraceSpan {spanId:string;parentSpanId:string|null;service:string;operation:string;start:string;end:string;durationMicros:number;status:string;attributes:Record<string,string>}
export interface TraceView {traceId:string;spans:TraceSpan[];projectIds:string[]}
export type EvidenceStatus='CONFIRMED_FACT'|'STRONG_EVIDENCE'|'PROBABLE_INFERENCE'|'POSSIBLE_HYPOTHESIS';
export interface EvidenceRef {id:string;kind:'LOG'|'TRACE'|'METRIC';sourceId:string;timestamp:string;service:string|null;label:string;link:string;status:EvidenceStatus;provenance:Record<string,string>}
export interface InvestigationTimeline {timestamp:string;uncertaintyEnd:string;service:string;host:string|null;summary:string;evidenceId:string;status:EvidenceStatus;firstFailure:boolean;downstreamSymptom:boolean}
export interface InvestigationResult {id:string;query:{projectId:string;environmentId:string|null;from:string;to:string;identifierType:string;identifierValue:string|null};deterministic:{summary:string;confidence:EvidenceStatus;timeline:InvestigationTimeline[];evidence:EvidenceRef[];exceptionPatterns:{fingerprint:string;exceptionType:string|null;normalizedMessage:string;occurrences:number;services:string[];evidenceIds:string[]}[];dependencyFlow:{parentService:string;childService:string;operation:string;evidenceId:string}[];affectedServices:string[];affectedHosts:string[];firstFailureEvidenceId:string|null;downstreamSymptoms:string[];qualityWarnings:string[]};ai:{rca:{summary:string;mostLikelyRootCause:string;confidence:EvidenceStatus;evidenceReferences:string[];timeline:InvestigationTimeline[];affectedServices:string[];downstreamSymptoms:string[];whyThisLikelyHappened:string;suggestedInvestigationSteps:string[];possibleRemediation:string[];uncertainties:string[]}|null;provider:string;model:string;latencyMs:number;outcome:string}}
