import { CommonModule } from '@angular/common';import { Component,computed,inject,signal } from '@angular/core';import { ActivatedRoute,Router } from '@angular/router';import { LogQueryApiService } from '../../core/api/log-query-api.service';import { ApiError,TraceSpan,TraceView } from '../../core/models/api.models';
@Component({standalone:true,imports:[CommonModule],template:`
<header class="page-header"><div><p class="eyebrow">DISTRIBUTED TRACE</p><h1>Trace waterfall</h1><p><code>{{traceId}}</code></p></div><div class="actions"><button class="primary" (click)="investigate()">Investigate</button><button (click)="relatedTraceLogs()">Related logs</button></div></header>
<div *ngIf="error()" class="error-banner" role="alert">{{error()}}</div><section class="panel" *ngIf="trace() as model;else loadingBlock"><div class="trace-summary"><span><strong>{{model.spans.length}}</strong> spans</span><span><strong>{{services()}}</strong> services</span><span><strong>{{duration()}}</strong> total</span><span><strong>{{errors()}}</strong> errors</span></div>
 <div class="waterfall-head"><span>Service / operation</span><span>Timeline</span><span>Duration</span></div><button class="span-row" *ngFor="let span of model.spans;trackBy:track" [class.error]="span.status==='ERROR'" [class.selected]="selected()?.spanId===span.spanId" (click)="selected.set(span)"><span class="span-name" [style.padding-left.px]="depth(span)*18"><i>{{depth(span)?'└─':'●'}}</i><strong>{{span.service}}</strong><small>{{span.operation}}</small></span><span class="timeline"><i [style.left.%]="offset(span)" [style.width.%]="width(span)"></i></span><span class="span-duration">{{formatDuration(span.durationMicros)}} <em>{{span.status}}</em></span></button>
</section><ng-template #loadingBlock><section class="panel empty-state" *ngIf="!error()">Loading authorized trace…</section></ng-template>
<aside class="detail-drawer" *ngIf="selected() as span"><div class="drawer-head"><div><p class="eyebrow">SPAN</p><h2>{{span.service}}</h2><code>{{span.spanId}}</code></div><button (click)="selected.set(null)">×</button></div><dl class="detail-grid"><dt>Operation</dt><dd>{{span.operation}}</dd><dt>Status</dt><dd><span class="level" [attr.data-level]="span.status==='ERROR'?'ERROR':'INFO'">{{span.status}}</span></dd><dt>Duration</dt><dd>{{formatDuration(span.durationMicros)}}</dd><dt>Started</dt><dd>{{span.start|date:'medium':'UTC'}} UTC</dd><dt>Parent</dt><dd><code>{{span.parentSpanId||'root'}}</code></dd></dl><h3>Safe attributes</h3><dl class="attributes"><ng-container *ngFor="let item of span.attributes|keyvalue"><dt>{{item.key}}</dt><dd>{{item.value}}</dd></ng-container></dl><div class="drawer-actions"><button class="primary" (click)="relatedSpanLogs(span)">Related logs</button></div></aside>
`})
export class TraceDetailComponent{
 private readonly api=inject(LogQueryApiService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);readonly trace=signal<TraceView|null>(null);readonly selected=signal<TraceSpan|null>(null);readonly error=signal('');readonly traceId=this.route.snapshot.paramMap.get('traceId')??'';private starts=0;private ends=1;
 readonly services=computed(()=>new Set(this.trace()?.spans.map(v=>v.service)??[]).size);readonly errors=computed(()=>this.trace()?.spans.filter(v=>v.status==='ERROR').length??0);readonly duration=computed(()=>{const spans=this.trace()?.spans??[];return spans.length?this.formatDuration((Math.max(...spans.map(v=>new Date(v.end).getTime()))-Math.min(...spans.map(v=>new Date(v.start).getTime())))*1000):'—';});
 constructor(){this.api.trace(this.traceId).subscribe({next:v=>{this.trace.set(v);this.starts=Math.min(...v.spans.map(s=>new Date(s.start).getTime()));this.ends=Math.max(...v.spans.map(s=>new Date(s.end).getTime()));this.selected.set(v.spans.find(s=>s.status==='ERROR')??v.spans[0]??null);},error:e=>{const x=e as {error?:ApiError};this.error.set(x.error?.message??'The trace is unavailable or outside your authorized scope.');}});}
 investigate(){const model=this.trace();if(!model?.projectIds.length)return;const starts=model.spans.map(v=>new Date(v.start).getTime()),ends=model.spans.map(v=>new Date(v.end).getTime());void this.router.navigate(['/investigations'],{queryParams:{projectId:model.projectIds[0],identifierType:'TRACE_ID',identifierValue:this.traceId,question:'What failed first in this trace?',from:new Date(Math.min(...starts)-60_000).toISOString(),to:new Date(Math.max(...ends)+60_000).toISOString()}});}depth(span:TraceSpan){const byId=new Map((this.trace()?.spans??[]).map(v=>[v.spanId,v]));let depth=0,parent=span.parentSpanId,seen=new Set<string>();while(parent&&byId.has(parent)&&!seen.has(parent)&&depth<12){seen.add(parent);depth++;parent=byId.get(parent)?.parentSpanId??null;}return depth;}offset(span:TraceSpan){return ((new Date(span.start).getTime()-this.starts)/Math.max(1,this.ends-this.starts))*100;}width(span:TraceSpan){return Math.max(.8,((new Date(span.end).getTime()-new Date(span.start).getTime())/Math.max(1,this.ends-this.starts))*100);}formatDuration(micros:number){if(micros>=1_000_000)return (micros/1_000_000).toFixed(2)+' s';if(micros>=1000)return (micros/1000).toFixed(1)+' ms';return micros+' µs';}track(_:number,span:TraceSpan){return span.spanId;}relatedTraceLogs(){void this.router.navigate(['/logs'],{queryParams:{traceId:this.traceId}});}relatedSpanLogs(span:TraceSpan){void this.router.navigate(['/logs'],{queryParams:{traceId:this.traceId,spanId:span.spanId}});}
}
