import { CommonModule } from '@angular/common';import { Component,inject,signal } from '@angular/core';import { FormsModule } from '@angular/forms';import { ActivatedRoute } from '@angular/router';import { InvestigationResult } from '../../core/models/api.models';import { LogQueryApiService } from '../../core/api/log-query-api.service';import { ScopePickerComponent,ScopeSelection } from '../../shared/components/scope-picker/scope-picker.component';
@Component({standalone:true,imports:[CommonModule,FormsModule,ScopePickerComponent],template:`
<header class="page-header"><div><p class="eyebrow">DETERMINISTIC + AI RCA</p><h1>Investigation</h1><p>Correlate authorized logs, traces, and allowlisted metrics before generating a grounded explanation.</p></div></header>
<app-scope-picker (scopeChange)="scopeChanged($event)" />
<section class="panel investigation-input"><label for="question">What happened?</label><textarea id="question" [(ngModel)]="question" maxlength="500" rows="3" placeholder="Why did order demo-order-42 fail?"></textarea><div class="actions"><select [(ngModel)]="rangeMinutes"><option [ngValue]="30">Last 30 minutes</option><option [ngValue]="60">Last hour</option><option [ngValue]="360">Last 6 hours</option><option [ngValue]="1440">Last 24 hours</option></select><button class="primary" (click)="investigate()" [disabled]="loading()||!scope.projectId">{{loading()?'Investigating…':'Investigate'}}</button></div><small>Questions are mapped to a sealed query model. No model-generated SQL is executed.</small></section>
<div *ngIf="error()" class="error-banner">{{error()}}</div>
<ng-container *ngIf="result() as r"><section class="panel rca-hero"><div><p class="eyebrow">INVESTIGATION SUMMARY</p><h2>{{r.ai.rca?.summary||r.deterministic.summary}}</h2><p *ngIf="r.ai.rca"><strong>Most likely root cause:</strong> {{r.ai.rca!.mostLikelyRootCause}}</p><p *ngIf="!r.ai.rca" class="uncertain">AI explanation unavailable; deterministic investigation remains complete.</p></div><span class="confidence" [attr.data-confidence]="r.ai.rca?.confidence||r.deterministic.confidence">{{r.ai.rca?.confidence||r.deterministic.confidence}}</span></section>
<div class="investigation-grid"><section class="panel"><h2>Timeline</h2><ol class="incident-timeline"><li *ngFor="let event of r.deterministic.timeline" [class.first]="event.firstFailure" [class.symptom]="event.downstreamSymptom"><time>{{event.timestamp|date:'HH:mm:ss.SSS':'UTC'}} UTC</time><div><strong>{{event.service}}</strong><p>{{event.summary}}</p><small>{{event.status}} · ±{{uncertainty(event)}} ms · <a [href]="evidenceLink(r,event.evidenceId)">{{event.evidenceId}}</a></small></div></li></ol></section><section class="panel"><h2>Affected services</h2><div class="service-cloud"><span *ngFor="let service of r.deterministic.affectedServices">{{service}}</span></div><h3>Failure chain</h3><p *ngFor="let edge of r.deterministic.dependencyFlow">{{edge.parentService}} → {{edge.childService}} <small>{{edge.operation}} · {{edge.evidenceId}}</small></p><p *ngFor="let symptom of r.deterministic.downstreamSymptoms" class="symptom-text">Downstream · {{symptom}}</p></section></div>
<section class="panel"><h2>Evidence</h2><div class="evidence-list"><article *ngFor="let item of r.deterministic.evidence" [attr.data-kind]="item.kind"><span>{{item.kind}}</span><div><strong>{{item.label}}</strong><small>{{item.status}} · {{item.service||'platform'}} · <a [href]="item.link">{{item.id}}</a></small></div></article></div></section>
<div class="investigation-grid"><section class="panel"><h2>Suggested actions</h2><ul><li *ngFor="let step of r.ai.rca?.suggestedInvestigationSteps">{{step}}</li><li *ngFor="let step of r.ai.rca?.possibleRemediation">{{step}}</li></ul></section><section class="panel uncertainties"><h2>Unknowns / uncertainties</h2><ul><li *ngFor="let warning of r.deterministic.qualityWarnings">{{warning}}</li><li *ngIf="!r.deterministic.qualityWarnings.length">No material evidence-quality warnings.</li></ul></section></div></ng-container>
`})export class InvestigationComponent{private readonly api=inject(LogQueryApiService);private readonly route=inject(ActivatedRoute);readonly result=signal<InvestigationResult|null>(null);readonly loading=signal(false);readonly error=signal('');scope:ScopeSelection={projectId:null,environmentId:null,serverId:null,serviceId:null};question=this.route.snapshot.queryParamMap.get('question')??'';rangeMinutes=30;private presetProject=this.route.snapshot.queryParamMap.get('projectId');private presetEnvironment=this.route.snapshot.queryParamMap.get('environmentId');private presetFrom=this.route.snapshot.queryParamMap.get('from');private presetTo=this.route.snapshot.queryParamMap.get('to');private identifierType=this.route.snapshot.queryParamMap.get('identifierType');private identifierValue=this.route.snapshot.queryParamMap.get('identifierValue');scopeChanged(v:ScopeSelection){this.scope={...v,projectId:this.presetProject??v.projectId,environmentId:this.presetEnvironment??v.environmentId};}investigate(){if(!this.scope.projectId)return;const to=this.presetTo?new Date(this.presetTo):new Date(),from=this.presetFrom?new Date(this.presetFrom):new Date(to.getTime()-this.rangeMinutes*60_000);this.loading.set(true);this.error.set('');this.api.investigate({question:this.question,projectId:this.scope.projectId,environmentId:this.scope.environmentId,from:from.toISOString(),to:to.toISOString(),identifierType:this.identifierType,identifierValue:this.identifierValue}).subscribe({next:r=>{this.result.set(r);this.loading.set(false);},error:e=>{this.error.set(e.error?.message??'Investigation failed.');this.loading.set(false);}});}uncertainty(event:{timestamp:string;uncertaintyEnd:string}){return Math.max(0,new Date(event.uncertaintyEnd).getTime()-new Date(event.timestamp).getTime());}evidenceLink(r:InvestigationResult,id:string){return r.deterministic.evidence.find(v=>v.id===id)?.link??'#';}}
