import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { InvestigationResult } from '../../core/models/api.models';
import { LogQueryApiService } from '../../core/api/log-query-api.service';
import { ScopePickerComponent, ScopeSelection } from '../../shared/components/scope-picker/scope-picker.component';

@Component({standalone:true,imports:[CommonModule,FormsModule,ScopePickerComponent],template:`
<header class="page-header"><div><p class="eyebrow">DETERMINISTIC INVESTIGATION</p><h1>Root-cause investigation</h1><p>Correlate authorized logs, traces, and allowlisted metrics into one inspectable evidence chain.</p></div><span class="trust-chip"><i class="pi pi-shield"></i> Evidence bounded</span></header>
<app-scope-picker (scopeChange)="scopeChanged($event)" />
<section class="panel investigation-input"><div class="input-heading"><div><span class="input-icon"><i class="pi pi-sparkles"></i></span><span><strong>Start an investigation</strong><small>Questions map to a sealed query model. No model-generated SQL or PromQL is executed.</small></span></div><span class="status-chip neutral">DETERMINISTIC FIRST</span></div><textarea id="question" [(ngModel)]="question" maxlength="500" rows="2" placeholder="Why did order demo-order-42 fail?"></textarea><div class="actions"><select aria-label="Investigation time range" [(ngModel)]="rangeMinutes"><option [ngValue]="30">Last 30 minutes</option><option [ngValue]="60">Last hour</option><option [ngValue]="360">Last 6 hours</option><option [ngValue]="1440">Last 24 hours</option></select><button class="primary" (click)="investigate()" [disabled]="loading()||!scope.projectId"><i class="pi" [class.pi-spin]="loading()" [class.pi-spinner]="loading()" [class.pi-search]="!loading()"></i>{{loading()?' Correlating evidence...':' Investigate'}}</button></div></section>
<div *ngIf="error()" class="error-banner" role="alert"><i class="pi pi-exclamation-circle"></i>{{error()}}</div>
@if(loading()){<section class="investigation-loading"><span></span><strong>Reconstructing the evidence timeline</strong><small>Ordering logs, spans, and bounded metric evidence.</small></section>}
@if(!loading()&&!result()){<section class="panel investigation-empty"><i class="pi pi-compass"></i><h2>Start with an identifier or operational question</h2><p>Open an investigation from a log, trace, order token, correlation ID, or the selected authorized scope.</p><div class="demo-hint"><span>DEMO PATH</span><code>demo-order-42</code><small>Demo Marketplace / PROD</small></div></section>}
<ng-container *ngIf="result() as r">
  <section class="investigation-banner"><div><p class="eyebrow">INVESTIGATION</p><div class="investigation-id"><h1>{{r.query.identifierValue || shortId(r.id)}}</h1><code>{{shortId(r.id)}}</code></div></div><div class="result-status"><span class="status-chip success"><i class="pi pi-check"></i> COMPLETED</span><span class="confidence" [attr.data-confidence]="r.ai.rca?.confidence||r.deterministic.confidence">{{label(r.ai.rca?.confidence||r.deterministic.confidence)}}</span></div></section>
  <section class="panel root-cause-hero"><div class="root-cause-icon"><i class="pi pi-bolt"></i></div><div><p class="eyebrow">ROOT CAUSE / FIRST FAILURE</p><h2>{{rootCause(r)}}</h2><p>{{r.deterministic.summary}}</p><div class="root-meta"><span><i class="pi pi-clock"></i>{{firstFailure(r).timestamp | date:'MMM d, HH:mm:ss.SSS':'UTC'}} UTC</span><span><i class="pi pi-box"></i>{{firstFailure(r).service || 'Correlated services'}}</span><span><i class="pi pi-link"></i>{{r.deterministic.firstFailureEvidenceId || 'Evidence linked'}}</span></div></div><span class="cause-label">EARLIEST SUPPORTED</span></section>
  <div class="investigation-grid hero-grid"><section class="panel"><div class="panel-heading"><div><p class="eyebrow">FAILURE CHAIN</p><h2>What happened, in order</h2></div><span>{{r.deterministic.timeline.length}} events</span></div><ol class="incident-timeline failure-chain"><li *ngFor="let event of r.deterministic.timeline" [class.first]="event.firstFailure" [class.symptom]="event.downstreamSymptom"><time>{{event.timestamp|date:'HH:mm:ss.SSS':'UTC'}}</time><div class="timeline-node"><i></i></div><div class="timeline-content"><div><strong>{{event.service}}</strong><span *ngIf="event.firstFailure" class="status-chip first">FIRST FAILURE</span><span *ngIf="event.downstreamSymptom" class="status-chip warning">DOWNSTREAM SYMPTOM</span></div><p>{{event.summary}}</p><small>{{label(event.status)}} / uncertainty {{uncertainty(event)}} ms / <a [href]="evidenceLink(r,event.evidenceId)">{{event.evidenceId}}</a></small></div></li></ol></section>
  <aside class="investigation-side"><section class="panel"><p class="eyebrow">AFFECTED SERVICES</p><h2>Impact surface</h2><div class="service-cloud"><span *ngFor="let service of r.deterministic.affectedServices"><i class="pi pi-box"></i>{{service}}</span></div><h3>Dependency flow</h3><div class="dependency-edge" *ngFor="let edge of r.deterministic.dependencyFlow"><strong>{{edge.parentService}}</strong><i class="pi pi-arrow-right"></i><strong>{{edge.childService}}</strong><small>{{edge.operation}}</small></div></section>
  <section class="panel ai-boundary"><div class="panel-heading"><div><p class="eyebrow">AI ANALYSIS BOUNDARY</p><h2>Deterministic development provider</h2></div><i class="pi pi-shield"></i></div><dl><dt>Provider</dt><dd>{{r.ai.provider}}</dd><dt>Model</dt><dd>{{r.ai.model}}</dd><dt>Outcome</dt><dd>{{r.ai.outcome}}</dd><dt>Latency</dt><dd>{{r.ai.latencyMs}} ms</dd></dl><p><strong>No external LLM call.</strong> The included stub validates the bounded structured RCA contract and evidence citations.</p></section></aside></div>
  <section class="panel evidence-section"><div class="panel-heading"><div><p class="eyebrow">EVIDENCE</p><h2>Grounded references</h2><p>Every conclusion remains inspectable at its source.</p></div><span class="evidence-count">{{r.deterministic.evidence.length}} REFERENCES</span></div><div class="evidence-grid"><a class="evidence-card" *ngFor="let item of r.deterministic.evidence" [attr.data-kind]="item.kind" [href]="item.link"><span class="evidence-kind"><i class="pi" [class.pi-align-left]="item.kind==='LOG'" [class.pi-share-alt]="item.kind==='TRACE'" [class.pi-chart-line]="item.kind==='METRIC'"></i>{{item.kind}}</span><strong>{{item.label}}</strong><small>{{item.service||'platform'}} / {{item.timestamp|date:'HH:mm:ss.SSS':'UTC'}} UTC</small><footer><code>{{item.id}}</code><span>{{label(item.status)}}</span></footer></a></div></section>
  <div class="investigation-grid"><section class="panel"><p class="eyebrow">SUGGESTED ACTIONS</p><h2>Next verification steps</h2><ul class="action-list"><li *ngFor="let step of r.ai.rca?.suggestedInvestigationSteps"><i class="pi pi-search"></i>{{step}}</li><li *ngFor="let step of r.ai.rca?.possibleRemediation"><i class="pi pi-wrench"></i>{{step}}</li><li *ngIf="!r.ai.rca"><i class="pi pi-info-circle"></i>No provider-generated suggestions. Deterministic findings remain complete.</li></ul></section><section class="panel uncertainties"><p class="eyebrow">UNCERTAINTIES</p><h2>Evidence quality</h2><ul><li *ngFor="let warning of r.deterministic.qualityWarnings">{{warning}}</li><li *ngIf="!r.deterministic.qualityWarnings.length"><i class="pi pi-check-circle"></i>No material evidence-quality warnings.</li></ul></section></div>
</ng-container>`})
export class InvestigationComponent {
  private readonly api=inject(LogQueryApiService); private readonly route=inject(ActivatedRoute);
  private readonly presetProject=this.route.snapshot.queryParamMap.get('projectId'); private readonly presetEnvironment=this.route.snapshot.queryParamMap.get('environmentId'); private readonly presetFrom=this.route.snapshot.queryParamMap.get('from'); private readonly presetTo=this.route.snapshot.queryParamMap.get('to'); private readonly identifierType=this.route.snapshot.queryParamMap.get('identifierType'); private readonly identifierValue=this.route.snapshot.queryParamMap.get('identifierValue');
  readonly result=signal<InvestigationResult|null>(null); readonly loading=signal(false); readonly error=signal('');
  scope:ScopeSelection={projectId:this.presetProject,environmentId:this.presetEnvironment,serverId:null,serviceId:null}; question=this.route.snapshot.queryParamMap.get('question')??''; rangeMinutes=30;
  scopeChanged(v:ScopeSelection){this.scope={...v,projectId:this.presetProject??v.projectId,environmentId:this.presetEnvironment??v.environmentId};}
  investigate(){if(!this.scope.projectId)return;const to=this.presetTo?new Date(this.presetTo):new Date(),from=this.presetFrom?new Date(this.presetFrom):new Date(to.getTime()-this.rangeMinutes*60_000);this.loading.set(true);this.error.set('');this.result.set(null);this.api.investigate({question:this.question,projectId:this.scope.projectId,environmentId:this.scope.environmentId,from:from.toISOString(),to:to.toISOString(),identifierType:this.identifierType,identifierValue:this.identifierValue}).subscribe({next:r=>{this.result.set(r);this.loading.set(false);},error:e=>{this.error.set(e.error?.message??'The investigation could not be completed for this authorized scope.');this.loading.set(false);}});}
  uncertainty(event:{timestamp:string;uncertaintyEnd:string}){return Math.max(0,new Date(event.uncertaintyEnd).getTime()-new Date(event.timestamp).getTime());}
  evidenceLink(r:InvestigationResult,id:string){return r.deterministic.evidence.find(v=>v.id===id)?.link??'#';}
  shortId(value:string){return value.length>18?value.slice(0,8)+'...'+value.slice(-6):value;}
  label(value:string|undefined){return (value||'UNKNOWN').replaceAll('_',' ');}
  firstFailure(r:InvestigationResult){return r.deterministic.timeline.find(event=>event.firstFailure)??r.deterministic.timeline[0];}
  rootCause(r:InvestigationResult){return r.ai.rca?.mostLikelyRootCause||this.firstFailure(r)?.summary||r.deterministic.summary;}
}
