package com.logatron.administration.web;
import com.logatron.administration.application.AdministrationService;import com.logatron.administration.application.AdministrationService.UserView;import com.logatron.administration.web.AdminDtos.*;import com.logatron.catalog.web.CatalogDtos.*;import io.swagger.v3.oas.annotations.Operation;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/v1/admin") public class AdministrationController{private final AdministrationService service;public AdministrationController(AdministrationService service){this.service=service;}
 @PostMapping("/projects") @Operation(summary="Create a project (global administrator)") public CreatedResource project(@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody CreateProjectRequest body,HttpServletRequest request){return service.createProject(jwt,body,request);}
 @PostMapping("/environments") public CreatedResource environment(@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody CreateEnvironmentRequest body,HttpServletRequest request){return service.createEnvironment(jwt,body,request);}
 @PostMapping("/servers") public CreatedResource server(@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody CreateServerRequest body,HttpServletRequest request){return service.createServer(jwt,body,request);}
 @PostMapping("/services") public CreatedResource service(@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody CreateServiceRequest body,HttpServletRequest request){return service.createService(jwt,body,request);}
 @PostMapping("/service-instances") public CreatedResource instance(@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody CreateInstanceRequest body,HttpServletRequest request){return service.createInstance(jwt,body,request);}
 @PostMapping("/log-sources") public CreatedResource source(@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody CreateLogSourceRequest body,HttpServletRequest request){return service.createLogSource(jwt,body,request);}
 @GetMapping("/users") public List<UserView> users(@AuthenticationPrincipal Jwt jwt){return service.users(jwt);}
 @GetMapping("/projects/{projectId}/access") public List<AccessView> access(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID projectId){return service.access(jwt,projectId);}
 @PostMapping("/memberships") public CreatedResource membership(@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody CreateMembershipRequest body,HttpServletRequest request){return service.createMembership(jwt,body,request);}
 @PostMapping("/environment-grants") public CreatedResource grant(@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody CreateGrantRequest body,HttpServletRequest request){return service.createGrant(jwt,body,request);}
 @PutMapping("/projects/{id}") public void updateProject(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@Valid @RequestBody UpdateProjectRequest body,HttpServletRequest request){service.updateProject(jwt,id,body,request);}
 @PutMapping("/environments/{id}") public void updateEnvironment(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@Valid @RequestBody UpdateEnvironmentRequest body,HttpServletRequest request){service.updateEnvironment(jwt,id,body,request);}
 @PutMapping("/servers/{id}") public void updateServer(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@Valid @RequestBody UpdateServerRequest body,HttpServletRequest request){service.updateServer(jwt,id,body,request);}
 @PutMapping("/services/{id}") public void updateService(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@Valid @RequestBody UpdateServiceRequest body,HttpServletRequest request){service.updateService(jwt,id,body,request);}
 @PutMapping("/service-instances/{id}") public void updateInstance(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@Valid @RequestBody UpdateInstanceRequest body,HttpServletRequest request){service.updateInstance(jwt,id,body,request);}
 @PutMapping("/log-sources/{id}") public void updateLogSource(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,@Valid @RequestBody UpdateLogSourceRequest body,HttpServletRequest request){service.updateLogSource(jwt,id,body,request);}
 @DeleteMapping("/memberships/{id}") public void deleteMembership(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,HttpServletRequest request){service.deleteMembership(jwt,id,request);}
 @DeleteMapping("/environment-grants/{id}") public void deleteGrant(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID id,HttpServletRequest request){service.deleteGrant(jwt,id,request);}
}
