package com.logatron.logquery.web;
import com.logatron.logquery.application.*;import com.logatron.logquery.domain.LogSearchCriteria;import com.logatron.logquery.web.LogQueryDtos.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.http.MediaType;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.web.bind.annotation.*;import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;import java.time.Instant;import java.util.UUID;
@RestController @RequestMapping("/api/v1")
public class LogQueryController{
 private final LogQueryService logs;private final LiveTailService live;public LogQueryController(LogQueryService logs,LiveTailService live){this.logs=logs;this.live=live;}
 @PostMapping("/logs/search")public SearchPage search(@AuthenticationPrincipal Jwt jwt,@RequestBody(required=false)LogSearchCriteria criteria,HttpServletRequest request){return logs.search(jwt,criteria==null?empty():criteria,request);}
 @GetMapping("/logs/{eventId}")public LogDetail detail(@AuthenticationPrincipal Jwt jwt,@PathVariable UUID eventId,HttpServletRequest request){return logs.detail(jwt,eventId,request);}
 @PostMapping("/logs/context")public ContextResponse context(@AuthenticationPrincipal Jwt jwt,@RequestBody ContextRequest input,HttpServletRequest request){return logs.context(jwt,input,request);}
 @PostMapping("/logs/correlate")public SearchPage correlate(@AuthenticationPrincipal Jwt jwt,@RequestBody CorrelateRequest input,HttpServletRequest request){return logs.correlate(jwt,input,request);}
 @PostMapping("/overview")public Overview overviewPost(@AuthenticationPrincipal Jwt jwt,@RequestBody(required=false)OverviewRequest input,HttpServletRequest request){return logs.overview(jwt,input,request);}
 @GetMapping("/overview")public Overview overview(@AuthenticationPrincipal Jwt jwt,@RequestParam(required=false)UUID projectId,@RequestParam(required=false)UUID environmentId,@RequestParam(required=false)UUID serviceId,@RequestParam(required=false)Instant from,@RequestParam(required=false)Instant to,HttpServletRequest request){return logs.overview(jwt,new OverviewRequest(projectId,environmentId,serviceId,from,to),request);}
 @GetMapping(value="/logs/live",produces=MediaType.TEXT_EVENT_STREAM_VALUE)public SseEmitter live(@AuthenticationPrincipal Jwt jwt,@RequestParam(required=false)UUID projectId,@RequestParam(required=false)UUID environmentId,@RequestParam(required=false)UUID serverId,@RequestParam(required=false)UUID serviceId,@RequestParam(required=false)String level,@RequestParam(required=false)String traceId,@RequestParam(required=false)String requestId,@RequestParam(required=false)String correlationId,@RequestParam(required=false)String transactionId,@RequestParam(required=false)String orderToken,@RequestParam(required=false)String auctionId,@RequestParam(required=false)String exceptionType,@RequestParam(required=false)String text,HttpServletRequest request){return live.open(jwt,new LogSearchCriteria(projectId,environmentId,serverId,serviceId,level,null,null,traceId,null,requestId,correlationId,transactionId,orderToken,auctionId,exceptionType,text,100,null),request);}
 private LogSearchCriteria empty(){return new LogSearchCriteria(null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,100,null);}
}
