package com.logatron.investigation.application;
import com.logatron.investigation.domain.InvestigationModels.*;import com.logatron.logquery.web.LogQueryDtos.LogRow;import org.springframework.stereotype.Component;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.*;import java.util.regex.Pattern;import java.util.stream.Collectors;
@Component public class DeterministicInvestigationEngine {
 private static final Set<String> ERROR=Set.of("ERROR","FATAL");private static final Pattern VARIABLE=Pattern.compile("(?i)([0-9a-f]{8}-[0-9a-f-]{27,}|\\b\\d+\\b|0x[0-9a-f]+)");
 public DeterministicResult analyze(List<LogRow> source,List<DependencyEdge> dependencies,List<MetricSeries> metrics){
  List<String> warnings=new ArrayList<>();if(source.isEmpty())warnings.add("No authorized logs matched the controlled investigation query.");
  LinkedHashMap<UUID,LogRow> unique=new LinkedHashMap<>();for(LogRow l:source)unique.putIfAbsent(l.eventId(),l);if(unique.size()<source.size())warnings.add("Duplicate event IDs were collapsed before analysis.");
  List<LogRow> logs=new ArrayList<>(unique.values());boolean ordered=true;for(int i=1;i<logs.size();i++)if(logs.get(i).timestamp().isBefore(logs.get(i-1).timestamp())){ordered=false;break;}if(!ordered)warnings.add("Out-of-order input was reordered using event timestamps.");logs.sort(Comparator.comparing(LogRow::timestamp).thenComparing(LogRow::eventId));
  Set<String> services=logs.stream().map(LogRow::service).filter(Objects::nonNull).collect(Collectors.toCollection(LinkedHashSet::new));Set<String> hosts=logs.stream().map(LogRow::server).filter(v->v!=null&&!v.isBlank()).collect(Collectors.toCollection(LinkedHashSet::new));if(logs.stream().anyMatch(v->blank(v.traceId())))warnings.add("One or more events lack a trace ID; cross-service linkage is lower confidence.");
  LogRow first=logs.stream().filter(this::failure).findFirst().orElse(null);List<EvidenceRef> evidence=new ArrayList<>();List<TimelineEvent> timeline=new ArrayList<>();
  for(LogRow l:logs){String id="log:"+l.eventId();EvidenceStatus status=EvidenceStatus.CONFIRMED_FACT;evidence.add(new EvidenceRef(id,EvidenceKind.LOG,l.eventId().toString(),l.timestamp(),l.service(),trim(l.message(),240),"/logs?eventId="+l.eventId(),status,Map.of("projectId",l.projectId().toString(),"environmentId",l.environmentId().toString())));boolean downstream=first!=null&&l.timestamp().isAfter(first.timestamp())&&isRetryOrSymptom(l);timeline.add(new TimelineEvent(l.timestamp(),l.timestamp().plusMillis(500),l.service(),l.server(),trim(l.message(),240),id,status,l==first,downstream));}
  Instant traceTime=logs.isEmpty()?null:logs.getFirst().timestamp();for(DependencyEdge edge:dependencies){services.add(edge.parentService());services.add(edge.childService());String[] parts=edge.evidenceId().split(":",4);String traceId=parts.length>1?parts[1]:edge.evidenceId();evidence.add(new EvidenceRef(edge.evidenceId(),EvidenceKind.TRACE,traceId,traceTime,edge.childService(),edge.parentService()+" → "+edge.childService()+" · "+edge.operation(),"/traces/"+traceId,EvidenceStatus.STRONG_EVIDENCE,Map.of("relation","parent-child span")));}
  List<String> downstream=new ArrayList<>(timeline.stream().filter(TimelineEvent::downstreamSymptom).map(v->v.service()+": "+v.summary()).distinct().toList());List<ExceptionPattern> patterns=patterns(logs);
  correlateMetrics(metrics,first,evidence,timeline,downstream,warnings);timeline.sort(Comparator.comparing(TimelineEvent::timestamp));evidence.sort(Comparator.comparing(EvidenceRef::timestamp,Comparator.nullsLast(Comparator.naturalOrder())));
  TimelineEvent firstCandidate=timeline.stream().filter(TimelineEvent::firstFailure).min(Comparator.comparing(TimelineEvent::timestamp)).orElse(null);String firstId=firstCandidate==null?null:firstCandidate.evidenceId();if(firstId!=null)timeline.replaceAll(v->new TimelineEvent(v.timestamp(),v.uncertaintyEnd(),v.service(),v.host(),v.summary(),v.evidenceId(),v.status(),firstId.equals(v.evidenceId()),v.downstreamSymptom()));EvidenceStatus confidence=firstCandidate==null?EvidenceStatus.POSSIBLE_HYPOTHESIS:(warnings.isEmpty()?EvidenceStatus.STRONG_EVIDENCE:EvidenceStatus.PROBABLE_INFERENCE);String summary=firstCandidate==null?"Evidence is insufficient to identify a first failure.":"The earliest supported failure candidate was "+firstCandidate.summary()+" in "+firstCandidate.service()+" at "+firstCandidate.timestamp()+"; later retry/duplicate signals are classified as downstream symptoms when supported by chronology.";
  return new DeterministicResult(summary,confidence,List.copyOf(timeline),List.copyOf(evidence),patterns,List.copyOf(dependencies),Set.copyOf(services),Set.copyOf(hosts),firstId,List.copyOf(downstream),List.copyOf(warnings));
 }
 private void correlateMetrics(List<MetricSeries> series,LogRow first,List<EvidenceRef> evidence,List<TimelineEvent> timeline,List<String> downstream,List<String> warnings){for(MetricSeries s:series){if(s.points()==null||s.points().isEmpty())continue;MetricPoint peak=s.points().stream().max(Comparator.comparingDouble(MetricPoint::value)).orElseThrow();boolean db=s.operation()==MetricOperation.DB_POOL_USAGE_RATIO&&peak.value()>=.9;boolean lag=s.operation()==MetricOperation.KAFKA_CONSUMER_LAG&&first!=null&&peak.timestamp().isAfter(first.timestamp());if(!db&&!lag)continue;String id="metric:"+s.operation()+":"+Math.abs(Objects.hash(s.service(),peak.timestamp()));String label=db?"DB connection pool saturation ("+Math.round(peak.value()*100)+"%)":"Kafka consumer lag increased to "+Math.round(peak.value());EvidenceStatus status=EvidenceStatus.STRONG_EVIDENCE;evidence.add(new EvidenceRef(id,EvidenceKind.METRIC,s.queryReference(),peak.timestamp(),s.service(),label,"/investigations/metrics?ref="+id,status,Map.of("operation",s.operation().name(),"unit",s.unit())));timeline.add(new TimelineEvent(peak.timestamp(),peak.timestamp(),s.service(),null,label,id,status,db&&(first==null||peak.timestamp().isBefore(first.timestamp())),lag));if(lag)downstream.add(label);}}
 private List<ExceptionPattern> patterns(List<LogRow> logs){Map<String,List<LogRow>> grouped=logs.stream().filter(this::failure).collect(Collectors.groupingBy(v->fingerprint(v.exceptionType(),v.message()),LinkedHashMap::new,Collectors.toList()));return grouped.entrySet().stream().map(e->{LogRow sample=e.getValue().getFirst();return new ExceptionPattern(e.getKey(),sample.exceptionType(),normalize(sample.message()),e.getValue().size(),e.getValue().stream().map(LogRow::service).filter(Objects::nonNull).collect(Collectors.toSet()),e.getValue().stream().map(v->"log:"+v.eventId()).toList());}).toList();}
 private boolean failure(LogRow l){return ERROR.contains(l.level())||l.exceptionType()!=null&&!l.exceptionType().isBlank();}private boolean isRetryOrSymptom(LogRow l){String m=(l.message()+" "+l.exceptionType()).toLowerCase(Locale.ROOT);return m.contains("retry")||m.contains("duplicate")||m.contains("lag")||m.contains("timeout")||m.contains("downstream");}private static boolean blank(String v){return v==null||v.isBlank();}private static String normalize(String v){return VARIABLE.matcher(v==null?"":v).replaceAll("?").replaceAll("\\s+"," ").trim();}private static String fingerprint(String type,String message){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(((type==null?"":type)+"|"+normalize(message)).getBytes(StandardCharsets.UTF_8))).substring(0,16);}catch(Exception e){throw new IllegalStateException(e);}}private static String trim(String v,int n){if(v==null)return "";return v.substring(0,Math.min(n,v.length()));}
}
