package com.logatron.investigation.application;
import com.fasterxml.jackson.databind.ObjectMapper;import com.logatron.audit.application.AuditService;import com.logatron.auth.application.*;import com.logatron.common.error.ApiException;import com.logatron.investigation.application.InvestigationPorts.*;import com.logatron.investigation.configuration.InvestigationProperties;import com.logatron.investigation.domain.InvestigationModels.*;import com.logatron.investigation.persistence.*;import com.logatron.investigation.web.InvestigationDtos.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Clock;import java.util.*;
@Service public class InvestigationService {
 private static final Set<MetricOperation> METRICS=Set.of(MetricOperation.DB_POOL_USAGE_RATIO,MetricOperation.KAFKA_CONSUMER_LAG,MetricOperation.HTTP_ERROR_RATE,MetricOperation.HTTP_LATENCY_P95,MetricOperation.PROCESSOR_FAILURE_RATE,MetricOperation.PLATFORM_API_ERROR_RATE);
 private final AuthorizationService authorization;private final AuditService audit;private final ControlledInvestigationPlanner planner;private final LogEvidencePort logs;private final TraceEvidencePort traces;private final MetricQueryPort metrics;private final DeterministicInvestigationEngine engine;private final AiProvider ai;private final InvestigationProperties properties;private final InvestigationRepository repository;private final ObjectMapper mapper;
 public InvestigationService(AuthorizationService authorization,AuditService audit,ControlledInvestigationPlanner planner,LogEvidencePort logs,TraceEvidencePort traces,MetricQueryPort metrics,DeterministicInvestigationEngine engine,AiProvider ai,InvestigationProperties properties,InvestigationRepository repository,ObjectMapper mapper){this.authorization=authorization;this.audit=audit;this.planner=planner;this.logs=logs;this.traces=traces;this.metrics=metrics;this.engine=engine;this.ai=ai;this.properties=properties;this.repository=repository;this.mapper=mapper;}
 @Transactional public InvestigationResult create(Jwt jwt,CreateInvestigationRequest input,HttpServletRequest request){AuthenticatedUser actor=authorization.authenticatedUser(jwt);InvestigationQuery query=planner.plan(input,Clock.systemUTC());EffectiveScope scope=authorization.resolveScope(actor);authorization.require(scope,new RequestedResourceScope(query.projectId(),query.environmentId(),null));UUID id=UUID.randomUUID();audit.record(actor,"INVESTIGATION_CREATE","INVESTIGATION",id,query.projectId(),query.environmentId(),"STARTED",Map.of("queryKind",query.identifierType().name(),"queryDigest",digest(query)),request);
  var authorizedLogs=logs.query(scope,query);audit.record(actor,"INVESTIGATION_EVIDENCE_ACCESS","INVESTIGATION",id,query.projectId(),query.environmentId(),"SUCCESS",Map.of("logCount",String.valueOf(authorizedLogs.size()),"scopeAppliedBeforeQuery","true"),request);var dependencies=traces.dependencies(jwt,authorizedLogs);var metricSeries=metrics.query(scope,query,METRICS);DeterministicResult deterministic=engine.analyze(authorizedLogs,dependencies,metricSeries);List<EvidenceRef> ranked=deterministic.evidence().stream().sorted(Comparator.comparing(EvidenceRef::status).thenComparing(EvidenceRef::timestamp,Comparator.nullsLast(Comparator.naturalOrder()))).limit(properties.maxEvidenceItems()).toList();AiResult aiResult=invokeAi(actor,id,query,deterministic,ranked,request);repository.save(new InvestigationEntity(id,actor.id(),query,digest(query),deterministic,aiResult));audit.record(actor,"INVESTIGATION_OUTCOME","INVESTIGATION",id,query.projectId(),query.environmentId(),"SUCCESS",Map.of("confidence",deterministic.confidence().name(),"evidenceCount",String.valueOf(deterministic.evidence().size()),"aiOutcome",aiResult.outcome()),request);return new InvestigationResult(id,query,deterministic,aiResult);}
 public StoredInvestigation get(Jwt jwt,UUID id,HttpServletRequest request){AuthenticatedUser actor=authorization.authenticatedUser(jwt);InvestigationEntity e=repository.findByIdAndOwnerUserId(id,actor.id()).orElseThrow(ApiException::notFound);authorization.require(authorization.resolveScope(actor),new RequestedResourceScope(e.getProjectId(),e.getEnvironmentId(),null));audit.record(actor,"INVESTIGATION_EVIDENCE_ACCESS","INVESTIGATION",id,e.getProjectId(),e.getEnvironmentId(),"SUCCESS",Map.of("storedReferencesOnly","true"),request);return StoredInvestigation.from(e);}
 private AiResult invokeAi(AuthenticatedUser actor,UUID id,InvestigationQuery q,DeterministicResult d,List<EvidenceRef> ranked,HttpServletRequest request){long start=System.nanoTime();try{EvidencePackage pack=new EvidencePackage(id,q.projectId(),q.environmentId(),q.from(),q.to(),bounded(d,ranked),ranked,properties.maxEvidenceItems(),"investigation-evidence-v1");AiResult result=ai.explain(pack);validate(result,ranked);audit.record(actor,"AI_INVOCATION","INVESTIGATION",id,q.projectId(),q.environmentId(),"SUCCESS",Map.of("provider",result.provider(),"model",result.model(),"latencyMs",String.valueOf(result.latencyMs()),"promptStored","false"),request);return result;}catch(RuntimeException ex){long latency=(System.nanoTime()-start)/1_000_000;audit.record(actor,"AI_INVOCATION","INVESTIGATION",id,q.projectId(),q.environmentId(),"FAILED",Map.of("provider",properties.aiProvider(),"model",properties.aiModel(),"latencyMs",String.valueOf(latency),"promptStored","false"),request);return new AiResult(null,properties.aiProvider(),properties.aiModel(),latency,"UNAVAILABLE_OR_REJECTED");}}
 private void validate(AiResult result,List<EvidenceRef> evidence){if(result==null||result.rca()==null||result.rca().summary()==null||result.rca().mostLikelyRootCause()==null)throw new IllegalArgumentException("Malformed AI output");Set<String> allowed=new HashSet<>();evidence.forEach(v->allowed.add(v.id()));if(!allowed.containsAll(result.rca().evidenceReferences()))throw new IllegalArgumentException("AI output cited unsupported evidence");}
 private DeterministicResult bounded(DeterministicResult d,List<EvidenceRef> evidence){Set<String> ids=new HashSet<>();evidence.forEach(v->ids.add(v.id()));List<TimelineEvent> timeline=d.timeline().stream().filter(v->ids.contains(v.evidenceId())).limit(properties.maxEvidenceItems()).toList();return new DeterministicResult(d.summary(),d.confidence(),timeline,evidence,d.exceptionPatterns().stream().limit(20).toList(),d.dependencyFlow().stream().filter(v->ids.contains(v.evidenceId())).limit(20).toList(),d.affectedServices(),d.affectedHosts(),d.firstFailureEvidenceId(),d.downstreamSymptoms().stream().limit(20).toList(),d.qualityWarnings());}
 private String digest(Object value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(mapper.writeValueAsString(value).getBytes(StandardCharsets.UTF_8)));}catch(Exception ex){return "unavailable";}}
}
