import { inject,Injectable } from '@angular/core';import { HttpClient,HttpParams } from '@angular/common/http';import { environment } from '../../../environments/environment';import { AuthService } from '../auth/auth.service';import { ContextResponse,InvestigationResult,LogDetail,LogRow,LogSearchCriteria,Overview,SavedSearch,SearchPage,TraceView } from '../models/api.models';
@Injectable({providedIn:'root'})
export class LogQueryApiService{
 private readonly http=inject(HttpClient);private readonly auth=inject(AuthService);private readonly base=`${environment.apiBaseUrl}/v1`;
 search(criteria:LogSearchCriteria){return this.http.post<SearchPage>(`${this.base}/logs/search`,criteria);}detail(id:string){return this.http.get<LogDetail>(`${this.base}/logs/${id}`);}context(eventId:string,before=50,after=50){return this.http.post<ContextResponse>(`${this.base}/logs/context`,{eventId,before,after});}
 correlate(projectId:string|null,environmentId:string|null,identifierType:string,value:string){return this.http.post<SearchPage>(`${this.base}/logs/correlate`,{projectId,environmentId,identifierType,value,pageSize:500});}
 overview(criteria:{projectId?:string|null;environmentId?:string|null;serviceId?:string|null;from?:string;to?:string}){return this.http.post<Overview>(`${this.base}/overview`,criteria);}
 saved(){return this.http.get<SavedSearch[]>(`${this.base}/saved-searches`);}save(name:string,visibility:'OWNER'|'PROJECT',criteria:LogSearchCriteria){return this.http.post<SavedSearch>(`${this.base}/saved-searches`,{name,visibility,criteria});}removeSaved(id:string){return this.http.delete<void>(`${this.base}/saved-searches/${id}`);}
 trace(traceId:string){return this.http.get<TraceView>(`${this.base}/traces/${traceId}`);}
 investigate(input:{question:string;projectId:string;environmentId:string|null;from:string;to:string;identifierType?:string|null;identifierValue?:string|null}){return this.http.post<InvestigationResult>(`${this.base}/investigations`,input);}
 async live(criteria:LogSearchCriteria,abort:AbortSignal,onLog:(row:LogRow)=>void,onStatus:(status:string)=>void){
  let params=new HttpParams();for(const [key,value] of Object.entries(criteria))if(value!==null&&value!==undefined&&value!==''&&!['from','to','cursor','pageSize'].includes(key))params=params.set(key,String(value));
  const response=await fetch(`${this.base}/logs/live?${params.toString()}`,{headers:{Authorization:`Bearer ${this.auth.token()??''}`,Accept:'text/event-stream'},signal:abort});if(!response.ok)throw new Error(`Live tail failed (${response.status})`);if(!response.body)throw new Error('Live tail streaming is unavailable.');
  const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let boundary;while((boundary=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);let event='message',data='';for(const line of frame.split(/\r?\n/)){if(line.startsWith('event:'))event=line.slice(6).trim();if(line.startsWith('data:'))data+=line.slice(5).trim();}if(!data)continue;if(event==='log')onLog(JSON.parse(data) as LogRow);else if(event==='status')onStatus(JSON.parse(data).state??event);else if(event==='error')throw new Error(JSON.parse(data).message??'Live tail interrupted.');}}}
}
