package com.logatron.integration;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.test.context.DynamicPropertyRegistry;import org.springframework.test.context.DynamicPropertySource;import org.springframework.test.web.servlet.MockMvc;import org.testcontainers.containers.PostgreSQLContainer;import org.testcontainers.junit.jupiter.*;import java.util.UUID;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@Testcontainers(disabledWithoutDocker=true) @SpringBootTest(properties="spring.profiles.active=dev-auth") @AutoConfigureMockMvc
class SecurityApiIntegrationTest{@Container static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:17.6-alpine").withDatabaseName("logatron").withUsername("logatron").withPassword("test-password");@DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("spring.datasource.url",POSTGRES::getJdbcUrl);r.add("spring.datasource.username",POSTGRES::getUsername);r.add("spring.datasource.password",POSTGRES::getPassword);}@Autowired MockMvc mvc;
 private org.springframework.test.web.servlet.request.RequestPostProcessor developer(){return jwt().jwt(j->j.issuer("http://localhost:8080/dev-auth").subject("developer").claim("aud",java.util.List.of("log-a-tron-api")));}
 @Test void unauthenticatedRequestIsRejected()throws Exception{mvc.perform(get("/api/v1/me")).andExpect(status().isUnauthorized());}
 @Test void developerSeesOnlyAssignedProject()throws Exception{mvc.perform(get("/api/v1/projects").with(developer())).andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(1)).andExpect(jsonPath("$[0].name").value("Demo Marketplace"));}
 @Test void crossProjectEnumerationReturnsNotFound()throws Exception{mvc.perform(get("/api/v1/projects/10000000-0000-0000-0000-000000000002/environments").with(developer())).andExpect(status().isNotFound()).andExpect(jsonPath("$.errorCode").value("RESOURCE_NOT_FOUND"));}
 @Test void developerCannotReadProdServers()throws Exception{mvc.perform(get("/api/v1/environments/20000000-0000-0000-0000-000000000003/servers").with(developer())).andExpect(status().isNotFound());}
}
