import { Component,inject,OnInit,signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ButtonModule } from 'primeng/button';import { SelectModule } from 'primeng/select';import { TableModule } from 'primeng/table';import { InputTextModule } from 'primeng/inputtext';import { MessageModule } from 'primeng/message';
import { CatalogApiService } from '../../core/api/catalog-api.service';
import { CollectorAgentView,CollectorConfigRevision,CompanyView,EnvironmentView,LogSourceView,ProjectView,ServerView,ServiceInstanceView,ServiceView } from '../../core/models/api.models';

@Component({standalone:true,imports:[FormsModule,ButtonModule,SelectModule,TableModule,InputTextModule,MessageModule],template:`
<header class="page-header"><div><p class="eyebrow">ENTERPRISE ONBOARDING</p><h1>Administration & onboarding</h1><p>Install one generic shipper per server. After that, environments, services, log sources, parser profiles and desired collector configuration are managed here and audited by the backend.</p></div></header>
<div class="panel onboarding-intro"><div><strong>1. Select project</strong><small>Choose the authorized application boundary.</small></div><i class="pi pi-angle-right"></i><div><strong>2. Model server + services</strong><small>Monolith or many microservices.</small></div><i class="pi pi-angle-right"></i><div><strong>3. Register shipper</strong><small>One manual install per server.</small></div><i class="pi pi-angle-right"></i><div><strong>4. Add log sources</strong><small>Future changes require no SSH.</small></div></div>
<div class="panel"><label>Project to administer</label><p-select class="admin-project" [options]="projects()" optionLabel="name" optionValue="id" [(ngModel)]="projectId" [fluid]="true" placeholder="Choose project" (onChange)="loadProject()" />@if(message()){<p-message [severity]="messageSeverity()">{{message()}}</p-message>}</div>
@if(companies().length){<div class="panel"><h2>Create project</h2><p class="help">Global administrators can create a new application boundary without backend changes.</p><div class="compact-form"><p-select [options]="companies()" optionLabel="name" optionValue="id" [(ngModel)]="newProject.companyId" placeholder="Company" /><input pInputText [(ngModel)]="newProject.slug" placeholder="project-slug" /><input pInputText [(ngModel)]="newProject.name" placeholder="Project name" /><p-select [options]="classifications" [(ngModel)]="newProject.classification" /><p-button label="Create project" icon="pi pi-plus" (onClick)="createProject()" [disabled]="!newProject.companyId||!newProject.slug||!newProject.name" /></div></div>}
<div class="admin-columns">
 <section class="panel"><h2>Environments</h2><p-table [value]="environments()"><ng-template #header><tr><th>Code</th><th>Name</th><th>Type</th></tr></ng-template><ng-template #body let-e><tr><td>{{e.code}}</td><td>{{e.name}}</td><td>{{e.type}}</td></tr></ng-template></p-table><h3>Add environment</h3><div class="compact-form"><input pInputText [(ngModel)]="newEnvironment.code" placeholder="UAT" /><input pInputText [(ngModel)]="newEnvironment.name" placeholder="UAT" /><p-button label="Create" icon="pi pi-plus" (onClick)="createEnvironment()" [disabled]="!ready(newEnvironment.code,newEnvironment.name)" /></div></section>
 <section class="panel"><h2>Logical services</h2><p-table [value]="services()"><ng-template #header><tr><th>Service</th><th>Criticality</th><th>Owner</th></tr></ng-template><ng-template #body let-s><tr><td>{{s.displayName}}</td><td>{{s.criticality}}</td><td>{{s.owner}}</td></tr></ng-template></p-table><h3>Add service</h3><div class="compact-form"><input pInputText [(ngModel)]="newService.key" placeholder="order-service" /><input pInputText [(ngModel)]="newService.name" placeholder="Order Service" /><p-button label="Create" icon="pi pi-plus" (onClick)="createService()" [disabled]="!ready(newService.key,newService.name)" /></div><p class="help">Model a monolith as one logical service or create each microservice independently. One server can host many service instances.</p></section>
 <section class="panel"><h2>Servers</h2><label>Environment</label><p-select [options]="environments()" optionLabel="code" optionValue="id" [(ngModel)]="environmentId" [fluid]="true" placeholder="Choose environment" (onChange)="loadServers()" /><p-table [value]="servers()"><ng-template #header><tr><th>Host ID</th><th>Hostname</th><th>Status</th><th>Collector</th><th></th></tr></ng-template><ng-template #body let-s><tr><td>{{s.hostId}}</td><td>{{s.hostname}}</td><td>{{s.status}}</td><td>{{s.collectorStatus}}</td><td><p-button label="Decommission" icon="pi pi-power-off" severity="danger" [outlined]="true" (onClick)="decommissionServer(s)" [disabled]="s.status==='OFFLINE'" /></td></tr></ng-template></p-table><h3>Add server</h3><div class="compact-form"><input pInputText [(ngModel)]="newServer.hostId" placeholder="application-uat-01" /><input pInputText [(ngModel)]="newServer.hostname" placeholder="hostname.internal" /><p-button label="Create" icon="pi pi-plus" (onClick)="createServer()" [disabled]="!environmentId||!ready(newServer.hostId,newServer.hostname)" /></div><p class="help">Decommissioning safely stops its instances and disables its sources. The shipper receives an empty desired configuration; historical logs remain searchable.</p></section>
 <section class="panel"><h2>Service instances</h2><label>Server</label><p-select [options]="servers()" optionLabel="hostname" optionValue="id" [(ngModel)]="serverId" [fluid]="true" placeholder="Choose server" (onChange)="loadInstancesAndAgent()" /><p-table [value]="instances()"><ng-template #header><tr><th>Instance</th><th>Service</th><th>Version</th></tr></ng-template><ng-template #body let-i><tr><td>{{i.instanceKey}}</td><td>{{i.serviceName}}</td><td>{{i.version}}</td></tr></ng-template></p-table><h3>Add instance</h3><div class="stack-form"><p-select [options]="services()" optionLabel="displayName" optionValue="id" [(ngModel)]="newInstance.serviceId" [fluid]="true" placeholder="Logical service" /><input pInputText [(ngModel)]="newInstance.key" placeholder="instance-key" /><input pInputText [(ngModel)]="newInstance.version" placeholder="Version" /><p-button label="Create instance" icon="pi pi-plus" (onClick)="createInstance()" [disabled]="!serverId||!newInstance.serviceId||!newInstance.key" /></div></section>

 <section class="panel managed-agent"><div class="panel-heading"><div><p class="eyebrow">MANAGED SHIPPER</p><h2>Collector agent</h2></div>@if(agent()){<span class="status-chip" [class.success]="agent()?.status==='ONLINE'&&agent()?.inSync" [class.warning]="agent()?.status==='DEGRADED'||!agent()?.inSync" [class.error]="agent()?.status==='OFFLINE'">{{agent()?.status}} · {{agent()?.inSync?'IN SYNC':'CONFIG PENDING'}}</span>}</div>
 @if(!serverId){<p class="help">Choose a server first.</p>}@else if(!agent()){<p>Register the generic shipper once for this server. The returned token is displayed only now; copy it to the server during installation.</p><div class="stack-form"><input pInputText [(ngModel)]="newAgent.key" placeholder="application-uat-01" /><input pInputText [(ngModel)]="newAgent.gateway" placeholder="Gateway reachable from server, e.g. 172.22.22.51:4317" /><label class="inline-check"><input type="checkbox" [(ngModel)]="newAgent.insecure" /> Use insecure OTLP for this environment</label><p-button label="Register managed shipper" icon="pi pi-link" (onClick)="registerAgent()" [disabled]="!newAgent.key||!newAgent.gateway" /></div>}@else{
   <dl class="detail-grid"><dt>Agent</dt><dd><code>{{agent()?.agentKey}}</code></dd><dt>Gateway</dt><dd>{{agent()?.gatewayEndpoint}}</dd><dt>Sources</dt><dd>{{agent()?.sourceCount}}</dd><dt>Collector</dt><dd>{{agent()?.collectorVersion||'Waiting for first heartbeat'}}</dd><dt>Last seen</dt><dd>{{agent()?.lastSeenAt||'Never'}}</dd><dt>Desired config</dt><dd>v{{agent()?.desiredConfigVersion}} · <code>{{shortHash(agent()?.desiredConfigHash)}}</code></dd><dt>Applied config</dt><dd>{{agent()?.appliedConfigVersion?'v'+agent()?.appliedConfigVersion:'—'}} · <code>{{shortHash(agent()?.appliedConfigHash)}}</code></dd></dl>
   @if(revisions().length){<h3>Configuration history</h3><p-table [value]="revisions()"><ng-template #header><tr><th>Version</th><th>Hash</th><th>Sources</th><th>State</th></tr></ng-template><ng-template #body let-r><tr><td>v{{r.configVersion}}</td><td><code>{{shortHash(r.configHash)}}</code></td><td>{{r.sourceCount}}</td><td>{{r.applied?'Applied':'Superseded / pending'}}</td></tr></ng-template></p-table>}
   <h3>Gateway desired state</h3><div class="compact-form"><input pInputText [(ngModel)]="agentGateway" placeholder="gateway.internal:4317" /><label class="inline-check"><input type="checkbox" [(ngModel)]="agentGatewayInsecure" /> Insecure</label><p-button label="Update" (onClick)="updateGateway()" /></div>
   <div class="actions"><p-button label="Rotate agent token" severity="secondary" icon="pi pi-refresh" (onClick)="rotateToken()" /><p-button label="Refresh status" severity="secondary" icon="pi pi-sync" (onClick)="loadAgent()" /></div>
   @if(agent()?.lastError){<p-message severity="error">{{agent()?.lastError}}</p-message>}
 }
 @if(agentToken()){<div class="bootstrap-token"><h3>One-time installation secret</h3><p>Copy this now. LOG-A-TRON stores only its hash.</p><code>{{agentToken()}}</code><pre>export LOGATRON_PLATFORM_URL='http://CONTROL-PLANE:8080'\nexport LOGATRON_AGENT_ID='{{agent()?.id}}'\nexport LOGATRON_AGENT_TOKEN='{{agentToken()}}'\n./logatron-managed-shipper.sh</pre></div>}
 </section>

 <section class="panel log-source-panel"><div class="panel-heading"><div><p class="eyebrow">DESIRED STATE</p><h2>Log sources</h2></div><span>{{sources().length}} configured</span></div><label>Service instance</label><p-select [options]="instances()" optionLabel="instanceKey" optionValue="id" [(ngModel)]="instanceId" [fluid]="true" placeholder="Choose instance" (onChange)="loadSources()" />
 <p-table [value]="sources()"><ng-template #header><tr><th>Path</th><th>Parser</th><th>Timezone</th><th>Multiline</th><th>Enabled</th><th>Actions</th></tr></ng-template><ng-template #body let-s><tr><td><code>{{s.pathPattern}}</code></td><td>{{s.parserProfile}}</td><td>{{s.timestampTimezone}}</td><td>{{multilineLabel(s)}}</td><td>{{s.enabled?'Yes':'No'}}</td><td><div class="actions"><p-button label="Edit" severity="secondary" (onClick)="editSource(s)" /><p-button [label]="s.enabled?'Disable':'Enable'" severity="secondary" (onClick)="toggleSource(s)" /></div></td></tr></ng-template></p-table>
 <h3>{{editingSourceId?'Edit':'Add'}} log source</h3><div class="stack-form"><input pInputText [(ngModel)]="newSource.path" placeholder="/logs/service/*.log or /logs/app/*/*.log" /><input pInputText [(ngModel)]="newSource.type" placeholder="application" /><p-select [options]="parserProfiles" [(ngModel)]="newSource.parser" [fluid]="true" placeholder="Parser profile" /><p-select [options]="timezones" [(ngModel)]="newSource.timezone" [editable]="true" [fluid]="true" placeholder="Timestamp timezone" /><p-select [options]="multilineModes" optionLabel="label" optionValue="value" [(ngModel)]="newSource.multilineMode" [fluid]="true" />@if(newSource.multilineMode==='CUSTOM'){<input pInputText [(ngModel)]="newSource.multilineRule" placeholder="Line-start regular expression" />}<label class="inline-check"><input type="checkbox" [(ngModel)]="newSource.enabled" /> Enabled</label><div class="actions"><p-button [label]="editingSourceId?'Save desired state':'Add to desired configuration'" icon="pi pi-save" (onClick)="saveSource()" [disabled]="!instanceId||!newSource.path||!newSource.type||!newSource.parser||!newSource.timezone||(newSource.multilineMode==='CUSTOM'&&!newSource.multilineRule)" />@if(editingSourceId){<p-button label="Cancel" severity="secondary" (onClick)="resetSourceForm()" />}</div></div><p class="help">Wildcard paths, parser, timezone, multiline and enabled state are compiled into a new immutable config revision. No server-side YAML edit is required.</p></section>

 <section class="panel"><h2>User / project access</h2><p-table [value]="access()"><ng-template #header><tr><th>User</th><th>Role</th></tr></ng-template><ng-template #body let-a><tr><td>{{a.displayName}}<small class="table-sub">{{a.user}}</small></td><td>{{a.role}}</td></tr></ng-template></p-table><h3>Add membership</h3><div class="stack-form"><p-select [options]="users()" optionLabel="displayName" optionValue="id" [(ngModel)]="newAccess.userId" [fluid]="true" placeholder="User" /><p-select [options]="roles" [(ngModel)]="newAccess.role" [fluid]="true" /><p-button label="Grant project role" icon="pi pi-user-plus" (onClick)="createMembership()" [disabled]="!projectId||!newAccess.userId" /></div></section>
</div>
`})
export class AdministrationComponent implements OnInit{
 private readonly api=inject(CatalogApiService);
 projects=signal<ProjectView[]>([]);companies=signal<CompanyView[]>([]);environments=signal<EnvironmentView[]>([]);services=signal<ServiceView[]>([]);servers=signal<ServerView[]>([]);instances=signal<ServiceInstanceView[]>([]);sources=signal<LogSourceView[]>([]);agent=signal<CollectorAgentView|null>(null);revisions=signal<CollectorConfigRevision[]>([]);agentToken=signal('');access=signal<Record<string,unknown>[]>([]);users=signal<{id:string;displayName:string}[]>([]);message=signal('');messageSeverity=signal<'success'|'error'>('success');
 readonly parserProfiles=['JSON','PLAINTEXT','JAVA_PIPE_V1','JAVA_PIPE_LEVEL_FIRST_V1'];readonly timezones=['UTC','Asia/Kolkata','Asia/Singapore','Europe/London','America/New_York'];readonly multilineModes=[{label:'Profile default',value:'DEFAULT'},{label:'Disabled',value:'DISABLED'},{label:'Custom line-start regex',value:'CUSTOM'}];readonly classifications=['PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED'];readonly roles=['PROJECT_ADMIN','PRODUCTION_SUPPORT','DEVELOPER','VIEWER','AUDITOR'];
 projectId:string|null=null;environmentId:string|null=null;serverId:string|null=null;instanceId:string|null=null;agentGateway='';agentGatewayInsecure=true;
 editingSourceId:string|null=null;newProject={companyId:'',slug:'',name:'',classification:'INTERNAL'};newEnvironment={code:'',name:''};newService={key:'',name:''};newServer={hostId:'',hostname:''};newInstance={serviceId:'',key:'',version:'1.0.0'};newSource={path:'',type:'application',parser:'JAVA_PIPE_V1',timezone:'Asia/Kolkata',multilineMode:'DEFAULT',multilineRule:'',enabled:true};newAgent={key:'',gateway:'',insecure:true};newAccess={userId:'',role:'VIEWER'};
 ngOnInit(){this.refreshProjects();this.api.companies().subscribe({next:v=>this.companies.set(v),error:()=>this.companies.set([])});this.api.adminUsers().subscribe({next:v=>this.users.set(v),error:()=>this.users.set([])});}
 ready(...values:string[]){return !!this.projectId&&values.every(Boolean);}
 loadProject(){this.environments.set([]);this.services.set([]);this.servers.set([]);this.instances.set([]);this.sources.set([]);this.agent.set(null);this.revisions.set([]);this.agentToken.set('');if(!this.projectId)return;this.api.environments(this.projectId).subscribe(v=>this.environments.set(v));this.api.services(this.projectId).subscribe(v=>this.services.set(v));this.api.access(this.projectId).subscribe({next:v=>this.access.set(v as Record<string,unknown>[]),error:()=>this.denied()});}
 loadServers(){this.servers.set([]);this.instances.set([]);this.sources.set([]);this.agent.set(null);this.serverId=null;this.instanceId=null;if(this.environmentId)this.api.servers(this.environmentId).subscribe(v=>this.servers.set(v));}
 loadInstancesAndAgent(){this.instances.set([]);this.sources.set([]);this.instanceId=null;this.agentToken.set('');if(!this.serverId){this.agent.set(null);return;}this.api.instances(this.serverId).subscribe(v=>this.instances.set(v));this.loadAgent();}
 loadAgent(){if(!this.serverId)return;this.api.collectorAgent(this.serverId).subscribe({next:v=>{this.agent.set(v);this.agentGateway=v?.gatewayEndpoint??'';this.agentGatewayInsecure=v?.gatewayInsecure??true;if(v)this.loadRevisions(v.id);else this.revisions.set([]);},error:()=>{this.agent.set(null);this.revisions.set([]);}});}
 loadSources(){this.sources.set([]);if(this.instanceId)this.api.logSources(this.instanceId).subscribe(v=>this.sources.set(v));}
 createProject(){this.api.createProject(this.newProject).subscribe({next:r=>{this.newProject={companyId:'',slug:'',name:'',classification:'INTERNAL'};this.projectId=r.id;this.refreshProjects(()=>this.loadProject());this.messageSeverity.set('success');this.message.set('Project created and audited.');},error:()=>this.denied()});}
 createEnvironment(){this.mutate(this.api.createEnvironment({projectId:this.projectId,code:this.newEnvironment.code,name:this.newEnvironment.name,type:this.newEnvironment.code.toUpperCase()==='PROD'?'PROD':'OTHER',sensitivity:'INTERNAL'}),()=>{this.newEnvironment={code:'',name:''};this.loadProject();},'Environment created');}
 createService(){this.mutate(this.api.createService({projectId:this.projectId,serviceKey:this.newService.key,displayName:this.newService.name,owner:'Unassigned',criticality:'MEDIUM',labels:{}}),()=>{this.newService={key:'',name:''};this.loadProject();},'Service created');}
 createServer(){this.mutate(this.api.createServer({environmentId:this.environmentId,hostId:this.newServer.hostId,hostname:this.newServer.hostname,labels:{}}),()=>{this.newServer={hostId:'',hostname:''};this.loadServers();},'Server created');}
 decommissionServer(server:ServerView){if(!confirm(`Decommission ${server.hostname}? Its service instances will stop and log sources will be disabled.`))return;this.mutate(this.api.decommissionServer(server.id),()=>this.loadServers(),'Server safely decommissioned; historical logs were retained');}
 createInstance(){this.mutate(this.api.createInstance({serviceId:this.newInstance.serviceId,serverId:this.serverId,instanceKey:this.newInstance.key,version:this.newInstance.version}),()=>{this.newInstance={serviceId:'',key:'',version:'1.0.0'};this.loadInstancesAndAgent();},'Service instance created');}
 saveSource(){const body={pathPattern:this.newSource.path,logType:this.newSource.type,parserProfile:this.newSource.parser,multilineRule:this.sourceMultilineRule(),timestampTimezone:this.newSource.timezone,enabled:this.newSource.enabled};const request=this.editingSourceId?this.api.updateLogSource(this.editingSourceId,body):this.api.createLogSource({serviceInstanceId:this.instanceId,...body});this.mutate(request,()=>{this.resetSourceForm();this.loadSources();this.loadAgent();},this.editingSourceId?'Log source updated':'Log source added to desired configuration');}
 editSource(source:LogSourceView){this.editingSourceId=source.id;this.newSource={path:source.pathPattern,type:source.logType,parser:source.parserProfile,timezone:source.timestampTimezone,multilineMode:source.multilineRule===null?'DEFAULT':source.multilineRule===''?'DISABLED':'CUSTOM',multilineRule:source.multilineRule??'',enabled:source.enabled};}
 toggleSource(source:LogSourceView){this.mutate(this.api.updateLogSource(source.id,{pathPattern:source.pathPattern,logType:source.logType,parserProfile:source.parserProfile,multilineRule:source.multilineRule,timestampTimezone:source.timestampTimezone,enabled:!source.enabled}),()=>{this.loadSources();this.loadAgent();},source.enabled?'Log source disabled':'Log source enabled');}
 resetSourceForm(){this.editingSourceId=null;this.newSource={path:'',type:'application',parser:'JAVA_PIPE_V1',timezone:'Asia/Kolkata',multilineMode:'DEFAULT',multilineRule:'',enabled:true};}
 multilineLabel(source:LogSourceView){return source.multilineRule===null?'Profile default':source.multilineRule===''?'Disabled':'Custom';}
 private sourceMultilineRule(){return this.newSource.multilineMode==='DEFAULT'?null:this.newSource.multilineMode==='DISABLED'?'':this.newSource.multilineRule;}
 registerAgent(){if(!this.serverId)return;this.api.registerCollectorAgent({serverId:this.serverId,agentKey:this.newAgent.key,gatewayEndpoint:this.newAgent.gateway,gatewayInsecure:this.newAgent.insecure}).subscribe({next:r=>{this.agent.set(r.agent);this.agentToken.set(r.token);this.agentGateway=r.agent.gatewayEndpoint;this.agentGatewayInsecure=r.agent.gatewayInsecure;this.messageSeverity.set('success');this.message.set('Managed shipper registered. Copy the one-time token now.');},error:()=>this.denied()});}
 rotateToken(){const a=this.agent();if(!a)return;this.api.rotateCollectorAgentToken(a.id).subscribe({next:r=>{this.agent.set(r.agent);this.agentToken.set(r.token);this.messageSeverity.set('success');this.message.set('Agent token rotated. Update the server with the new one-time token.');},error:()=>this.denied()});}
 updateGateway(){const a=this.agent();if(!a||!this.agentGateway)return;this.api.updateCollectorAgentGateway(a.id,{gatewayEndpoint:this.agentGateway,gatewayInsecure:this.agentGatewayInsecure}).subscribe({next:v=>{this.agent.set(v);this.loadRevisions(v.id);this.messageSeverity.set('success');this.message.set('Gateway desired state updated.');},error:()=>this.denied()});}
 createMembership(){this.mutate(this.api.createMembership({userId:this.newAccess.userId,projectId:this.projectId,role:this.newAccess.role}),()=>this.loadProject(),'Membership created');}
 shortHash(value:string|null|undefined){return value?value.slice(0,12)+'…':'—';}
 private refreshProjects(after?:()=>void){this.api.projects().subscribe(v=>{this.projects.set(v);after?.();});}
 private loadRevisions(agentId:string){this.api.collectorConfigRevisions(agentId).subscribe({next:v=>this.revisions.set(v),error:()=>this.revisions.set([])});}
 private mutate(request:{subscribe:(handlers:{next:()=>void;error:()=>void})=>unknown},after:()=>void,label:string){request.subscribe({next:()=>{this.messageSeverity.set('success');this.message.set(`${label} and audited.`);after();},error:()=>this.denied()});}
 private denied(){this.messageSeverity.set('error');this.message.set('Operation denied or invalid. Confirm project-admin scope and field values.');}
}
