package com.logatron.catalog.application;

import com.logatron.auth.application.*;import com.logatron.catalog.persistence.*;import com.logatron.catalog.web.CatalogDtos.*;import com.logatron.common.error.ApiException;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;

@Service @Transactional(readOnly=true) public class CatalogQueryService{
 private final AuthorizationService auth;private final ProjectRepository projects;private final EnvironmentRepository environments;private final ServerRepository servers;private final ServiceRepository services;private final ServiceInstanceRepository instances;private final LogSourceRepository sources;
 public CatalogQueryService(AuthorizationService auth,ProjectRepository projects,EnvironmentRepository environments,ServerRepository servers,ServiceRepository services,ServiceInstanceRepository instances,LogSourceRepository sources){this.auth=auth;this.projects=projects;this.environments=environments;this.servers=servers;this.services=services;this.instances=instances;this.sources=sources;}
 public List<ProjectView> projects(Jwt jwt){var scope=auth.resolveScope(jwt);return projects.findAllByIdInOrderByName(scope.projects().keySet()).stream().map(this::projectView).toList();}
 public ProjectView project(Jwt jwt,UUID id){var scope=auth.resolveScope(jwt);auth.require(scope,RequestedResourceScope.project(id));return projectView(projects.findById(id).orElseThrow(ApiException::notFound));}
 public List<EnvironmentView> environments(Jwt jwt,UUID projectId){var scope=auth.resolveScope(jwt);auth.require(scope,RequestedResourceScope.project(projectId));var ps=scope.projects().get(projectId);return environments.findByProjectIdAndIdInOrderByCode(projectId,ps.environmentIds()).stream().map(this::environmentView).toList();}
 public List<ServerView> servers(Jwt jwt,UUID environmentId){EnvironmentEntity env=environments.findById(environmentId).orElseThrow(ApiException::notFound);var scope=auth.resolveScope(jwt);auth.require(scope,RequestedResourceScope.environment(env.getProject().getId(),environmentId));return servers.findByEnvironmentIdOrderByHostname(environmentId).stream().map(this::serverView).toList();}
 public List<ServiceView> services(Jwt jwt,UUID projectId){var scope=auth.resolveScope(jwt);auth.require(scope,RequestedResourceScope.project(projectId));var ps=scope.projects().get(projectId);Set<UUID> restricted=ps.serviceIdsByEnvironment().values().stream().filter(s->!s.isEmpty()).collect(java.util.stream.Collector.of(HashSet::new,Set::addAll,(a,b)->{a.addAll(b);return a;}));boolean hasUnrestricted=ps.allEnvironments()||ps.serviceIdsByEnvironment().values().stream().anyMatch(Set::isEmpty);var rows=hasUnrestricted?services.findByProjectIdOrderByDisplayName(projectId):services.findByProjectIdAndIdInOrderByDisplayName(projectId,restricted);return rows.stream().map(this::serviceView).toList();}
 public List<ServiceInstanceView> instances(Jwt jwt,UUID serverId){ServerEntity server=servers.findById(serverId).orElseThrow(ApiException::notFound);var scope=auth.resolveScope(jwt);auth.require(scope,RequestedResourceScope.environment(server.getEnvironment().getProject().getId(),server.getEnvironment().getId()));return instances.findDetailedByServerId(serverId).stream().filter(i->allowedService(scope,server.getEnvironment().getProject().getId(),server.getEnvironment().getId(),i.getService().getId())).map(this::instanceView).toList();}
 public List<LogSourceView> logSources(Jwt jwt,UUID instanceId){ServiceInstanceEntity instance=instances.findById(instanceId).orElseThrow(ApiException::notFound);UUID projectId=instance.getService().getProject().getId(),environmentId=instance.getServer().getEnvironment().getId();var scope=auth.resolveScope(jwt);auth.require(scope,new RequestedResourceScope(projectId,environmentId,instance.getService().getId()));return sources.findDetailedByServiceInstanceId(instanceId).stream().map(this::sourceView).toList();}
 private boolean allowedService(EffectiveScope s,UUID p,UUID e,UUID service){try{auth.require(s,new RequestedResourceScope(p,e,service));return true;}catch(ApiException ex){return false;}}
 private ProjectView projectView(ProjectEntity p){return new ProjectView(p.getId(),p.getSlug(),p.getName(),p.getClassification(),p.getStatus(),environments.findByProjectIdOrderByCode(p.getId()).size(),servers.countByEnvironmentProjectId(p.getId()),services.countByProjectId(p.getId()),instances.countByServiceProjectId(p.getId()));}
 private EnvironmentView environmentView(EnvironmentEntity e){return new EnvironmentView(e.getId(),e.getProject().getId(),e.getCode(),e.getName(),e.getType(),e.getSensitivity(),e.getStatus());}
 private ServerView serverView(ServerEntity s){return new ServerView(s.getId(),s.getEnvironment().getId(),s.getHostId(),s.getHostname(),s.getIpAddress(),s.getStatus(),s.getLabels(),s.getCollectorStatus(),s.getCollectorLastSeenAt());}
 private ServiceView serviceView(ServiceEntity s){return new ServiceView(s.getId(),s.getProject().getId(),s.getServiceKey(),s.getDisplayName(),s.getOwner(),s.getCriticality(),s.getStatus(),s.getLabels());}
 private ServiceInstanceView instanceView(ServiceInstanceEntity i){return new ServiceInstanceView(i.getId(),i.getService().getId(),i.getService().getDisplayName(),i.getServer().getId(),i.getServer().getHostname(),i.getInstanceKey(),i.getVersion(),i.getStatus(),i.getFirstSeenAt(),i.getLastSeenAt());}
 private LogSourceView sourceView(LogSourceEntity l){return new LogSourceView(l.getId(),l.getServiceInstance().getId(),l.getPathPattern(),l.getLogType(),l.getParserProfile(),l.getMultilineRule(),l.isEnabled(),l.getConfigVersion());}
}

