package com.logatron.common.error;
public enum ErrorCode { INVALID_REQUEST, RESOURCE_NOT_FOUND, ACCESS_DENIED, UNAUTHENTICATED, CONFLICT, QUERY_TIMEOUT, DEPENDENCY_UNAVAILABLE, RATE_LIMITED, INTERNAL_ERROR }
